import Mathlib

open MeasureTheory

namespace WeightedMajority.Randomized

/-- Weights of WMR along a sample path `ω`, with zero-based update-trials `j = 0, 1, …`.
`w1 i > 0` is the deterministic initial weight of pool member `i` (the paper's `w_i^{(1)}`);
in trial `j` the weight of member `i` is multiplied by the factor `F j i (x j i ω) (ρ j ω)`,
a function of the member's prediction and of the label (the update step (5.1)). -/
noncomputable def weight {Ω : Type*} {n : ℕ} (w1 : Fin n → ℝ)
    (F : ℕ → Fin n → ℝ → ℝ → ℝ) (x : ℕ → Fin n → Ω → ℝ) (ρ : ℕ → Ω → ℝ) :
    ℕ → Fin n → Ω → ℝ
  | 0, i, _ => w1 i
  | j + 1, i, ω => F j i (x j i ω) (ρ j ω) * weight w1 F x ρ j i ω

/-- Total weight `s^{(j+1)}` at the beginning of zero-based trial `j`; `totalWeight … 0` is
`w_init` and `totalWeight … t` is `w_fin`. -/
noncomputable def totalWeight {Ω : Type*} {n : ℕ} (w1 : Fin n → ℝ)
    (F : ℕ → Fin n → ℝ → ℝ → ℝ) (x : ℕ → Fin n → Ω → ℝ) (ρ : ℕ → Ω → ℝ)
    (j : ℕ) (ω : Ω) : ℝ :=
  ∑ i : Fin n, weight w1 F x ρ j i ω

/-- The weighted average prediction `γ` of the pool in zero-based trial `j`, which is the
probability with which WMR predicts `1`. -/
noncomputable def gamma {Ω : Type*} {n : ℕ} (w1 : Fin n → ℝ)
    (F : ℕ → Fin n → ℝ → ℝ → ℝ) (x : ℕ → Fin n → Ω → ℝ) (ρ : ℕ → Ω → ℝ)
    (j : ℕ) (ω : Ω) : ℝ :=
  (∑ i : Fin n, weight w1 F x ρ j i ω * x j i ω) / totalWeight w1 F x ρ j ω

/-- Number of mistakes `m = Σ_{j<t} |λ^{(j)} − ρ^{(j)}|` of WMR over `t` trials. -/
def mistakes {Ω : Type*} (t : ℕ) (lam ρ : ℕ → Ω → ℝ) (ω : Ω) : ℝ :=
  ∑ j ∈ Finset.range t, |lam j ω - ρ j ω|

/-- The σ-algebra generated by `(x^{(1)}, ρ^{(1)}), …, (x^{(j+1)}, ρ^{(j+1)})`: the pool's
prediction vectors and the labels of the zero-based trials `0, …, j`, the current one
included. -/
@[reducible] def history {Ω : Type*} {n : ℕ} (x : ℕ → Fin n → Ω → ℝ) (ρ : ℕ → Ω → ℝ) (j : ℕ) :
    MeasurableSpace Ω :=
  ⨆ (k : ℕ) (_ : k ≤ j),
    MeasurableSpace.comap (fun ω => ((fun i => x k i ω), ρ k ω)) inferInstance

/-- The standing assumptions of WMR on `t` trials (§5–§6): `0 ≤ β < 1`; positive initial
weights; pool predictions in `[0,1]`, binary labels and binary master predictions, all
measurable random variables; measurable update factors satisfying (5.1) in every trial on
every sample path. -/
def IsWMRModel {Ω : Type*} [MeasurableSpace Ω] {n : ℕ} (t : ℕ) (β : ℝ) (w1 : Fin n → ℝ)
    (F : ℕ → Fin n → ℝ → ℝ → ℝ) (x : ℕ → Fin n → Ω → ℝ) (ρ lam : ℕ → Ω → ℝ) : Prop :=
  0 ≤ β ∧ β < 1 ∧
  (∀ i : Fin n, 0 < w1 i) ∧
  (∀ j < t, ∀ i : Fin n, Measurable (Function.uncurry (F j i))) ∧
  (∀ j < t, ∀ i : Fin n, Measurable (x j i)) ∧
  (∀ j < t, ∀ i : Fin n, ∀ ω, 0 ≤ x j i ω ∧ x j i ω ≤ 1) ∧
  (∀ j < t, Measurable (ρ j)) ∧
  (∀ j < t, ∀ ω, ρ j ω = 0 ∨ ρ j ω = 1) ∧
  (∀ j < t, Measurable (lam j)) ∧
  (∀ j < t, ∀ ω, lam j ω = 0 ∨ lam j ω = 1) ∧
  (∀ j < t, ∀ i : Fin n, ∀ ω,
    β ^ |x j i ω - ρ j ω| ≤ F j i (x j i ω) (ρ j ω) ∧
    F j i (x j i ω) (ρ j ω) ≤ 1 - (1 - β) * |x j i ω - ρ j ω|)

/-- The weak independence condition (p. 238):
`E(λ^{(j)} | (x^{(1)}, ρ^{(1)}), …, (x^{(j)}, ρ^{(j)})) = γ^{(j)}` almost surely, for every
trial. -/
def WeakIndependence {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) {n : ℕ} (t : ℕ)
    (w1 : Fin n → ℝ) (F : ℕ → Fin n → ℝ → ℝ → ℝ) (x : ℕ → Fin n → Ω → ℝ)
    (ρ lam : ℕ → Ω → ℝ) : Prop :=
  ∀ j < t, P[lam j | history x ρ j] =ᵐ[P] gamma w1 F x ρ j

end WeightedMajority.Randomized
