import Mathlib
import Definitions.Def_PalmQueueing_Ordering_PartialOrders

/-!
# Integral stochastic orderings (§4.2.1, p.272)

The family of orders Strassen's theorems are about. Mathlib has none of them: no stochastic order,
no convex order, no increasing-convex order.
-/

namespace PalmQueueing.Ordering

open MeasureTheory

/-- `𝒟(ℝⁿ)`, the set of probabilities on `ℝⁿ` (p.272). Carried as a predicate on measures rather
than as a subtype, so that a statement "for `F` and `G` in `𝒟(ℝⁿ)`" reads as a hypothesis.

The OCR of this book renders the script `𝒟` as both `D` and `V`; they are the same class. In
particular Theorem 4.2.2's "integrable distributions in `V(ℝⁿ)`" is `𝒟(ℝⁿ)`, the same class as
Theorem 4.2.1's. -/
def IsDistribution {n : ℕ} (F : Measure (Fin n → ℝ)) : Prop := IsProbabilityMeasure F

/-- `F ≤_ℒ G` (p.272): the **integral order** generated by a set `ℒ` of measurable mappings
`ℝⁿ → ℝ`,

`F ≤_ℒ G  if  ∫ f(x)F(dx) ≤ ∫ f(x)G(dx)  for all f ∈ ℒ such that the integrals are well defined.`

The qualification "such that the integrals are well defined" is the book's and is kept: it is what
lets the order be defined without an integrability hypothesis on `ℒ`. -/
def IntegralLe {n : ℕ} (L : Set ((Fin n → ℝ) → ℝ)) (F G : Measure (Fin n → ℝ)) : Prop :=
  ∀ f ∈ L, Integrable f F → Integrable f G → (∫ x, f x ∂F) ≤ ∫ x, f x ∂G

/-- `{i}`: the non-decreasing functions `ℝⁿ → ℝ`, generating the **increasing (partial) integral
order** `≤_i` on `𝒟(ℝⁿ)` (p.272). Remark 4.2.1: "Traditionally, the initials 'st' (for stochastic)
are used in place of 'i' (increasing). We will see that the `≤_i` order is in some sense equivalent
to the pathwise stochastic order associated with `≤`; we will thus often refer to it as the
**strong ordering**." -/
def classI (n : ℕ) : Set ((Fin n → ℝ) → ℝ) := {f | ∀ x y : Fin n → ℝ, CoordLe x y → f x ≤ f y}

/-- `{cx}`: the convex functions `ℝⁿ → ℝ`, generating the **convex integral order** `≤_cx`. -/
def classCx (n : ℕ) : Set ((Fin n → ℝ) → ℝ) := {f | ConvexOn ℝ Set.univ f}

/-- `{icx} = {i} ∩ {cx}`, generating the **increasing convex** ordering `≤_icx` on `𝒟(ℝⁿ)`. -/
def classIcx (n : ℕ) : Set ((Fin n → ℝ) → ℝ) := classI n ∩ classCx n

/-- `{scx}`: the Schur-convex functions, defining the **Schur-convex integral order** `≤_scx`. -/
def classScx (n : ℕ) : Set ((Fin n → ℝ) → ℝ) := {f | SchurConvex f}

/-- `{cxs}`: the convex symmetric functions, generating the **convex symmetric** ordering. -/
def classCxs (n : ℕ) : Set ((Fin n → ℝ) → ℝ) :=
  {f | ConvexOn ℝ Set.univ f ∧ ∀ (g : Equiv.Perm (Fin n)) (x : Fin n → ℝ), f (x ∘ g) = f x}

/-- `F ≤_i G`, the strong (stochastic) order. -/
def StLe {n : ℕ} (F G : Measure (Fin n → ℝ)) : Prop := IntegralLe (classI n) F G

/-- `F ≤_cx G`, the convex order. -/
def CxLe {n : ℕ} (F G : Measure (Fin n → ℝ)) : Prop := IntegralLe (classCx n) F G

/-- `F ≤_icx G`, the increasing convex order. -/
def IcxLe {n : ℕ} (F G : Measure (Fin n → ℝ)) : Prop := IntegralLe (classIcx n) F G

/-- A distribution on `ℝⁿ` is **integrable**: it has a finite first moment, which is the
hypothesis Theorem 4.2.2 carries and Theorem 4.2.1 does not. -/
def IsIntegrableDist {n : ℕ} (F : Measure (Fin n → ℝ)) : Prop :=
  Integrable (fun x : Fin n → ℝ => ‖x‖) F

end PalmQueueing.Ordering
