import Mathlib
import Definitions.Def_Disjunctive_GeneralDisjunctions_Basic

namespace Disjunctive.GeneralDisjunctions

/-- The LP cone `C(J)` with apex `xbar`, basic index set `I` and nonbasic (cobasis) index set
`J`, as a set: the cone generated by the `n = |J|` extreme rays `r^j`, `j ∈ J` (Balas §1.2, p. 3:
"`C(J)` has `n` extreme rays with direction vectors `r^j`, `j ∈ J`"). -/
def LPCone {ι : Type*} [Fintype ι] [DecidableEq ι] (I J : Finset ι) (abar : ι → ι → ℝ)
    (xbar : ι → ℝ) : Set (ι → ℝ) :=
  {x | ∃ lam : ι → ℝ, (∀ j ∈ J, 0 ≤ lam j) ∧ x = xbar + ∑ j ∈ J, lam j • extremeRay I abar j}

/-- `x` is an integer point on the coordinates indexed by `Nprime` (Balas §1.2, p. 3, the
integrality restriction of `P_I := P ∩ {x : x_j ∈ ℤ, j ∈ N' ⊆ N}`). -/
def IntegerPoint {ι : Type*} (Nprime : Finset ι) (x : ι → ℝ) : Prop :=
  ∀ j ∈ Nprime, ∃ k : ℤ, x j = (k : ℝ)

/-- The corner polyhedron `corner(J)`: the convex hull of the integer points (on coordinates
`Nprime`) contained in the LP cone `C(J)` (Balas §1.2, p. 3: "the convex hull of integer points
in `C(J)` is known as the corner polyhedron, denoted `corner(J)`"). -/
def cornerPolyhedron {ι : Type*} [Fintype ι] [DecidableEq ι] (I J : Finset ι) (abar : ι → ι → ℝ)
    (xbar : ι → ℝ) (Nprime : Finset ι) : Set (ι → ℝ) :=
  convexHull ℝ (LPCone I J abar xbar ∩ {x | IntegerPoint Nprime x})

end Disjunctive.GeneralDisjunctions
