import Mathlib
import Definitions.Def_DelayedSWPT_Model_dswpt

namespace DelayedSWPT.Extended

open DelayedSWPT.Model

/-- The doubled problem (2P) of §3.1, p. 689: release dates and processing times multiplied by
two, weights unchanged. -/
def double {n : ℕ} (I : Instance n) : Instance n where
  r j := 2 * I.r j
  p j := 2 * I.p j
  w := I.w
  p_pos j := by have := I.p_pos j; omega
  w_pos := I.w_pos

open Classical in
/-- `f(t)` of §3.2, p. 689: the first time at or after `t` at which the machine is available
in the Delayed SWPT schedule `π`. If a job `j` is in process at `t` and started before `t`
(`π j < t < π j + p j`), this is its completion time; otherwise it is `t` itself (in
particular when a job starts exactly at `t`). -/
noncomputable def f {n : ℕ} (I : Instance n) (t : ℕ) : ℕ :=
  if h : ∃ j, dswpt I j < t ∧ t < dswpt I j + I.p j then dswpt I h.choose + I.p h.choose else t

/-- The release dates of (P′), §3.2, p. 689: `r′ⱼ = max {pⱼ, f(rⱼ)}`. -/
noncomputable def rPrime {n : ℕ} (I : Instance n) (j : Fin n) : ℕ :=
  max (I.p j) (f I (I.r j))

/-- `t` is a gap time (§3.2, p. 689): the machine is available at `t`, Delayed SWPT selects an
available job `j`, and `p j > t`, so nothing is scheduled in `[t, t + 1)`. -/
def IsGapTime {n : ℕ} (I : Instance n) (t : ℕ) : Prop :=
  ∃ j, dswptChoice I t = some j ∧ t < I.p j

open Classical in
/-- The set of gap times `t` (one gap job `g_t` each). Every job of `π` starts before the
horizon, so no gap time lies at or beyond it. -/
noncomputable def gapTimes {n : ℕ} (I : Instance n) : Finset ℕ :=
  (Finset.range (horizon I.r I.p)).filter (IsGapTime I)

/-- The gap-generating job of the gap job `g_t`: the job selected by Delayed SWPT at `t`. -/
noncomputable def gapJob {n : ℕ} (I : Instance n) (g : gapTimes I) : Fin n :=
  (dswptChoice I g.1).get (by
    classical
    obtain ⟨j, hj, -⟩ := (Finset.mem_filter.1 g.2).2
    simp [hj])

/-- The jobs of the extended problem (E): the original jobs `J` and the gap jobs `G`. -/
abbrev EJob {n : ℕ} (I : Instance n) : Type := Fin n ⊕ gapTimes I

/-- Release dates of (E): `r′ⱼ` for `j ∈ J`, and `r′_{g_t} = f(r_j)` for the gap job `g_t`
generated by `j`. -/
noncomputable def rE {n : ℕ} (I : Instance n) : EJob I → ℕ :=
  Sum.elim (rPrime I) (fun g => f I (I.r (gapJob I g)))

/-- Processing times of (E): `pⱼ` for `j ∈ J`, and `1` for every gap job. -/
def pE {n : ℕ} (I : Instance n) : EJob I → ℕ :=
  Sum.elim I.p (fun _ => 1)

/-- The weight `w_{g_t} = w_j / p_j` of the gap job generated by `j`. -/
noncomputable def gapWeight {n : ℕ} (I : Instance n) (g : gapTimes I) : ℝ :=
  I.w (gapJob I g) / (I.p (gapJob I g) : ℝ)

/-- Weights of (E): `wⱼ` for `j ∈ J`, and `w_j / p_j` for the gap job generated by `j`. -/
noncomputable def wE {n : ℕ} (I : Instance n) : EJob I → ℝ :=
  Sum.elim I.w (gapWeight I)

/-- The schedule `π_E` of (E), §3.2, p. 690: each job of `J` starts as in `π`, and the gap job
`g_t` occupies the idle slot `[t, t + 1)`. -/
noncomputable def piE {n : ℕ} (I : Instance n) : EJob I → ℕ :=
  Sum.elim (dswpt I) (fun g => g.1)

end DelayedSWPT.Extended
