import Mathlib
import Definitions.Def_KallenbergLP_OptTransient_FiniteMDP

namespace KallenbergLP.OptTransient

/-- A decision rule at each time, depending on the entire state-action history (stored newest first). -/
abbrev Policy (n : ℕ) (α : Type) :=
  ℕ → List (Fin n × α) → Fin n → α → ℝ

/-- The book's policies: nonnegative distributions supported on available actions. -/
def IsPolicy {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α) (R : Policy n α) : Prop :=
  ∀ t h i, (∀ a, 0 ≤ R t h i a) ∧
    (∀ a, a ∉ m.actions i → R t h i a = 0) ∧
    (∑ a ∈ m.actions i, R t h i a) = 1

/-- A policy whose rule depends on time and state but not on history. -/
def IsMarkov {n : ℕ} {α : Type} (R : Policy n α) : Prop :=
  ∃ π : ℕ → Fin n → α → ℝ, ∀ t h i a, R t h i a = π t i a

/-- A policy using the same state-dependent distribution at each time. -/
def IsStationary {n : ℕ} {α : Type} (R : Policy n α) : Prop :=
  ∃ π : Fin n → α → ℝ, ∀ t h i a, R t h i a = π i a

/-- A stationary rule. -/
abbrev StationaryRule (n : ℕ) (α : Type) := Fin n → α → ℝ

/-- A stationary policy generated by a rule. -/
def stationaryPolicy {n : ℕ} {α : Type} (π : StationaryRule n α) : Policy n α :=
  fun _ _ i a => π i a

/-- A pure stationary policy selecting one available action in each state. -/
def purePolicy {n : ℕ} {α : Type} [DecidableEq α]
    (f : Fin n → α) : Policy n α :=
  fun _ _ i a => if a = f i then 1 else 0

/-- Probability of an ordered history of state-action pairs ending in the current state.
The list is stored newest first; time zero is the first decision epoch. -/
def historyMass {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α)
    (R : Policy n α) (initial : Fin n) : List (Fin n × α) → Fin n → ℝ
  | [], j => if j = initial then 1 else 0
  | (s :: h), j => historyMass m R initial h s.1 *
      R h.length h s.1 s.2 * m.transition s.1 s.2 j

/-- The probability of state `j` and action `a` at decision epoch `t+1`, given initial state `i`. -/
noncomputable def jointAt {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α) (R : Policy n α)
    (i : Fin n) (t : ℕ) (j : Fin n) (a : α) : ℝ :=
  ∑ h : Fin t → (Fin n × α),
    historyMass m R i (List.ofFn h) j * R t (List.ofFn h) j a

/-- Probability of state `j` at epoch `t+1`. -/
noncomputable def stateAt {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α) (R : Policy n α)
    (i : Fin n) (t : ℕ) (j : Fin n) : ℝ :=
  ∑ a ∈ m.actions j, jointAt m R i t j a

/-- Transience means finite expected visits to every state from every initial state. -/
def IsTransient {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α) (R : Policy n α) : Prop :=
  ∀ i j, Summable (fun t : ℕ => stateAt m R i t j)

/-- Expected total reward for a transient policy. -/
noncomputable def totalReward {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α) (R : Policy n α) (i : Fin n) : ℝ :=
  ∑' t : ℕ, ∑ s : StateAction m,
    jointAt m R i t s.1 s.2.1 * m.reward s.1 s.2.1

/-- Expected number of state-action visits weighted by positive initial weights β, (3.3.12). -/
noncomputable def occupation {n : ℕ} {α : Type} [Fintype α] [DecidableEq α]
    (m : FiniteSubstochasticMDP n α) (β : Fin n → ℝ) (R : Policy n α)
    (s : StateAction m) : ℝ :=
  ∑' t : ℕ, ∑ i : Fin n, β i * jointAt m R i t s.1 s.2.1

end KallenbergLP.OptTransient
