import Mathlib
import Definitions.Def_TotalVariationDist

namespace ChenStein.Process

open MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal

variable {Ω : Type*} [MeasurableSpace Ω] {I : Type*}

/-- `p_α = P(X_α = 1)`, the success probability of the Bernoulli variable `X_α`. -/
noncomputable def p (P : Measure Ω) (X : I → Ω → ℕ) (α : I) : ℝ :=
  P.real {ω | X α ω = 1}

/-- `p_{αβ} = E(X_α X_β)`. -/
noncomputable def pab (P : Measure Ω) (X : I → Ω → ℕ) (α β : I) : ℝ :=
  ∫ ω, ((X α ω : ℝ) * (X β ω : ℝ)) ∂P

/-- `σ(X_β : β ∈ I − B_α)`, the σ-algebra generated by the variables outside the
neighbourhood of dependence `B_α`. -/
@[instance_reducible]
noncomputable def farSigma (X : I → Ω → ℕ) (B : I → Set I) (α : I) : MeasurableSpace Ω :=
  ⨆ β ∈ (B α)ᶜ, MeasurableSpace.comap (X β) inferInstance

/-- `s_α = E|E{X_α − p_α | σ(X_β : β ∈ I − B_α)}|`, valued in `ℝ≥0∞`. -/
noncomputable def s (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) (α : I) : ℝ≥0∞ :=
  ∫⁻ ω, ‖(condExp (farSigma X B α) P (fun ω => (X α ω : ℝ) - p P X α)) ω‖ₑ ∂P

/-- `b₁ = Σ_{α ∈ I} Σ_{β ∈ B_α} p_α p_β`, valued in `ℝ≥0∞`. -/
noncomputable def b1 (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, ∑' β : B α, ENNReal.ofReal (p P X α * p P X β)

/-- `b₂ = Σ_{α ∈ I} Σ_{α ≠ β ∈ B_α} p_{αβ}`, valued in `ℝ≥0∞`. -/
noncomputable def b2 (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, ∑' β : {β // β ∈ B α ∧ β ≠ α}, ENNReal.ofReal (pab P X α β)

/-- `b₃ = Σ_{α ∈ I} s_α`, valued in `ℝ≥0∞`. -/
noncomputable def b3 (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, s P X B α

/-- The process `(X_α)_{α ∈ I}` as one random element of `ℕ^I`. -/
def Xproc (X : I → Ω → ℕ) : Ω → (I → ℕ) := fun ω α => X α ω

/-- The block sums `W_j = Σ_{α ∈ I(j)} X_α` of a partition `I(j) = part⁻¹{j}`,
as one random element of `ℕ^d` (ℕ-valued `tsum`). -/
noncomputable def Wvec {d : ℕ} (X : I → Ω → ℕ) (part : I → Fin d) : Ω → (Fin d → ℕ) :=
  fun ω j => ∑' α : {α // part α = j}, X α ω

/-- `λ_j = Σ_{α ∈ I(j)} p_α = E W_j`. -/
noncomputable def lamj {d : ℕ} (P : Measure Ω) (X : I → Ω → ℕ) (part : I → Fin d)
    (j : Fin d) : ℝ :=
  ∑' α : {α // part α = j}, p P X α

/-! ### Coordinatewise Stein operators on functions `(ℤ⁺)^d → ℝ` (§6, p. 22) -/

/-- The unit vector `e_i`. -/
def e {d : ℕ} (i : Fin d) : Fin d → ℕ := Pi.single i 1

/-- `(T_i f)(j) = j_i f(j) − λ_i f(j + e_i)`. -/
noncomputable def Ti {d : ℕ} (i : Fin d) (lj : ℝ≥0) (f : (Fin d → ℕ) → ℝ)
    (j : Fin d → ℕ) : ℝ :=
  (j i : ℝ) * f j - (lj : ℝ) * f (j + e i)

/-- `(S_i h)(j + e_i) = −(λ_i P(Z_i = j_i))^{−1} E{h(j₁,…,Z_i,…,j_d) 1(Z_i ≤ j_i)}`,
read at a point whose `i`-th coordinate is `n + 1`; the value at a point whose
`i`-th coordinate is `0` is fixed to `0`, as for `S` in §4. -/
noncomputable def Si {d : ℕ} (i : Fin d) (lj : ℝ≥0) (h : (Fin d → ℕ) → ℝ)
    (j : Fin d → ℕ) : ℝ :=
  match j i with
  | 0 => 0
  | n + 1 => -((lj : ℝ) * (poissonMeasure lj).real {n})⁻¹ *
      ∑ k ∈ Finset.range (n + 1), h (Function.update j i k) * (poissonMeasure lj).real {k}

/-- `(P_i h)(j) = E h(j₁,…,Z_i,…,j_d)` with `Z_i ~ Poisson(λ_i)`. -/
noncomputable def Pi_ {d : ℕ} (i : Fin d) (lj : ℝ≥0) (h : (Fin d → ℕ) → ℝ)
    (j : Fin d → ℕ) : ℝ :=
  ∫ k, h (Function.update j i k) ∂(poissonMeasure lj)

/-- `(Δ_i f)(j) = f(j + e_i) − f(j)`. -/
def Δi {d : ℕ} (i : Fin d) (f : (Fin d → ℕ) → ℝ) (j : Fin d → ℕ) : ℝ :=
  f (j + e i) - f j

end ChenStein.Process
