import Mathlib

namespace CalibratedCE.Forecast

/-- `S_T^{ij} = ∑_{t=1}^T w_t^i (L_t^i - L_t^j)` for `k` forecasts with losses `L t i` and
weights `w t i`; rounds are `0, …, T - 1`. -/
def S {k : ℕ} (L w : ℕ → Fin k → ℝ) (T : ℕ) (i j : Fin k) : ℝ :=
  ∑ t ∈ Finset.range T, w t i * (L t i - L t j)

/-- The regret `R_T^{i→j} = max{0, S_T^{ij}}` generated by changing all `i` forecasts to `j`
forecasts over the first `T` rounds. -/
def Rg {k : ℕ} (L w : ℕ → Fin k → ℝ) (T : ℕ) (i j : Fin k) : ℝ :=
  max 0 (S L w T i j)

end CalibratedCE.Forecast
