import Mathlib
import Definitions.Def_ThreeOpSplitting_ConvexRates_Problem

namespace NesterovFB.Rates

/-- The objective Θ = Ψ + Φ of problem (1), valued in ℝ ∪ {±∞} (Ψ may take the value +∞). -/
noncomputable def theta {H : Type*} (Ψ : H → EReal) (Φ : H → ℝ) (x : H) : EReal :=
  Ψ x + (Φ x : EReal)

/-- The extrapolated point y_k = x_k + (k−1)/(k+α−1)·(x_k − x_{k−1}) of algorithm (2). -/
noncomputable def extrap {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (α : ℝ) (x : ℕ → H) (k : ℕ) : H :=
  x k + (((k : ℝ) - 1) / ((k : ℝ) + α - 1)) • (x k - x (k - 1))

/-- (x_k) is generated by algorithm (2) from k = 1 on, with `P` playing the role of prox_{sΨ}:
x_{k+1} = P(y_k − s∇Φ(y_k)) for every k ≥ 1. -/
def IsAccelFBRun {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (Φ : H → ℝ) (P : H → H) (α s : ℝ) (x : ℕ → H) : Prop :=
  ∀ k : ℕ, 1 ≤ k → x (k + 1) = P (extrap α x k - s • gradient Φ (extrap α x k))

/-- The operator G_s(y) = (1/s)(y − prox_{sΨ}(y − s∇Φ(y))), with `P` playing the role of
prox_{sΨ}. -/
noncomputable def gradMap {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    [CompleteSpace H] (Φ : H → ℝ) (P : H → H) (s : ℝ) (y : H) : H :=
  (1 / s) • (y - P (y - s • gradient Φ y))

/-- The auxiliary sequence z_k = x_k + (k−1)/(α−1)·(x_k − x_{k−1}) of (6). -/
noncomputable def zSeq {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (α : ℝ) (x : ℕ → H) (k : ℕ) : H :=
  x k + (((k : ℝ) - 1) / (α - 1)) • (x k - x (k - 1))

/-- The energy (5):
E(k) = 2s/(α−1)·(k+α−2)²·(Θ(x_k) − Θ(x*)) + (α−1)‖z_k − x*‖², valued in ℝ ∪ {±∞}. -/
noncomputable def energy {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (Ψ : H → EReal) (Φ : H → ℝ) (α s : ℝ) (x : ℕ → H) (xstar : H) (k : ℕ) : EReal :=
  ((2 * s / (α - 1) * ((k : ℝ) + α - 2) ^ 2 : ℝ) : EReal) * (theta Ψ Φ (x k) - theta Ψ Φ xstar)
    + (((α - 1) * ‖zSeq α x k - xstar‖ ^ 2 : ℝ) : EReal)

end NesterovFB.Rates
