import Mathlib
import Definitions.Def_TotalVariationDist

namespace ChenStein.OneVar

open MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal

/-- The success probability of an indicator. -/
noncomputable def p {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (α : I) : ℝ :=
  P.real {ω | X α ω = 1}

/-- The joint success probability of two indicators. -/
noncomputable def pab {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (α β : I) : ℝ :=
  ∫ ω, (X α ω : ℝ) * (X β ω : ℝ) ∂P

/-- The number of events that occur. -/
noncomputable def W {Ω I : Type*} (X : I → Ω → ℕ) (ω : Ω) : ℕ :=
  ∑' α, X α ω

/-- The sigma-algebra generated by the indicators outside a neighbourhood. -/
noncomputable def farSigma {Ω I : Type*} [MeasurableSpace Ω]
    (X : I → Ω → ℕ) (B : I → Set I) (α : I) : MeasurableSpace Ω :=
  ⨆ β ∈ (B α)ᶜ, MeasurableSpace.comap (X β) inferInstance

/-- The number of events outside a neighbourhood. -/
noncomputable def V {Ω I : Type*} (X : I → Ω → ℕ)
    (B : I → Set I) (α : I) (ω : Ω) : ℕ :=
  ∑' β : ((B α)ᶜ : Set I), X β ω

/-- Conditional dependence on all far indicators. -/
noncomputable def s {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) (α : I) : ℝ≥0∞ :=
  ∫⁻ ω, ‖(P[fun ω => (X α ω : ℝ) - p P X α | farSigma X B α]) ω‖ₑ ∂P

/-- Conditional dependence on the number of far indicators. -/
noncomputable def s' {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) (α : I) : ℝ≥0∞ :=
  ∫⁻ ω, ‖(P[fun ω => (X α ω : ℝ) - p P X α |
      MeasurableSpace.comap (V X B α) inferInstance]) ω‖ₑ ∂P

/-- The product-of-marginals neighbourhood sum. -/
noncomputable def b1 {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, ∑' β : B α, ENNReal.ofReal (p P X α * p P X β)

/-- The pair-probability neighbourhood sum, excluding the diagonal. -/
noncomputable def b2 {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, ∑' β : {β : I // β ∈ B α ∧ β ≠ α},
    ENNReal.ofReal (pab P X α β)

/-- The sum of conditional dependence on all far indicators. -/
noncomputable def b3 {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, s P X B α

/-- The sum of conditional dependence on far event counts. -/
noncomputable def b3' {Ω I : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : I → Ω → ℕ) (B : I → Set I) : ℝ≥0∞ :=
  ∑' α, s' P X B α

/-- The Stein operator for the Poisson law. -/
def T (lam : ℝ) (f : ℕ → ℝ) : ℕ → ℝ :=
  fun w => (w : ℝ) * f w - lam * f (w + 1)

/-- The inverse Stein operator, fixed to zero at zero. -/
noncomputable def S (lam : ℝ≥0) (h : ℕ → ℝ) : ℕ → ℝ
  | 0 => 0
  | w + 1 => -((lam : ℝ)⁻¹) * (poissonPMFReal lam w)⁻¹ *
      ∑ k ∈ Finset.range (w + 1), h k * poissonPMFReal lam k

/-- Forward difference of a function on the nonnegative integers. -/
def Δ (f : ℕ → ℝ) : ℕ → ℝ := fun w => f (w + 1) - f w

/-- Expectation under the Poisson law. -/
noncomputable def poissonMean (lam : ℝ≥0) (h : ℕ → ℝ) : ℝ :=
  ∫ k, h k ∂(poissonMeasure lam)

end ChenStein.OneVar
