import Mathlib
import Definitions.Def_DiscountedDP_Stationary_Return

namespace DiscountedDP.Stationary

open MeasureTheory ProbabilityTheory

variable {S A : Type*} [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    [MeasurableSpace A] [StandardBorelSpace A] [Nonempty A]

/-- The sup norm on a bounded function, written as a real supremum. -/
noncomputable def supNorm (u : S → ℝ) : ℝ := ⨆ s : S, |u s|

/-- The one-step operator of a measurable decision rule, p. 230. -/
noncomputable def T (P : Problem S A) (f : {g : S → A // Measurable g})
    (u : S → ℝ) (s : S) : ℝ :=
  ∫ s', P.r (s, f.1 s, s') + P.β * u s' ∂P.q (s, f.1 s)

/-- The one-step operator for a constant action. -/
noncomputable def Ta (P : Problem S A) (a : A) (u : S → ℝ) (s : S) : ℝ :=
  ∫ s', P.r (s, a, s') + P.β * u s' ∂P.q (s, a)

/-- A rule assembled from a Markov plan's rules on a countable Borel partition. -/
def IsGenerated (π : MarkovPlan S A) (f : {g : S → A // Measurable g}) : Prop :=
  ∃ pieces : ℕ → Set S,
    (∀ n, MeasurableSet (pieces n)) ∧
    (∀ i j, i ≠ j → Disjoint (pieces i) (pieces j)) ∧
    (⋃ n, pieces n) = Set.univ ∧
    ∀ n s, s ∈ pieces n → f.1 s = (π n).1 s

/-- A Markov plan whose every decision rule is generated by `π`. -/
def IsGeneratedPlan (π π' : MarkovPlan S A) : Prop :=
  ∀ n, IsGenerated π (π' n)

/-- The operator associated with a Markov plan: pointwise supremum of its rule operators. -/
noncomputable def U (P : Problem S A) (π : MarkovPlan S A)
    (u : S → ℝ) (s : S) : ℝ :=
  ⨆ n : ℕ, T P (π n) u s

/-- Primary definition of equivalence of acts at a state, pp. 233–234. -/
def ActEquiv (P : Problem S A) (s : S) (a b : A) : Prop :=
  (∀ s', P.r (s, a, s') = P.r (s, b, s')) ∧ P.q (s, a) = P.q (s, b)

/-- Every action is represented at each state by a rule of `π`. -/
def EssCountable (P : Problem S A) (π : MarkovPlan S A) : Prop :=
  ∀ s a, ∃ n, ActEquiv P s ((π n).1 s) a

/-- On piece `n` of a countable Borel partition, the first `n+1` rules
represent every action, using Lean's zero-based stage indices. -/
def EssFinite (P : Problem S A) (π : MarkovPlan S A) : Prop :=
  ∃ pieces : ℕ → Set S,
    (∀ n, MeasurableSet (pieces n)) ∧
    (∀ i j, i ≠ j → Disjoint (pieces i) (pieces j)) ∧
    (⋃ n, pieces n) = Set.univ ∧
    ∀ n s, s ∈ pieces n → ∀ a, ∃ i ≤ n, ActEquiv P s ((π i).1 s) a

end DiscountedDP.Stationary
