import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Fintype.Card
import Mathlib.Tactic

/-!
# Finite probability laws and kernels (mission substrate)

Mission `Free Energy Principle I` shared finite substrate, transcribed from the
proved module `FepSketches.finite_probability` of the fep_lean formalization
(Active Inference Institute).  One normalized real-valued carrier for the
finite-state parts of the FEP: nonnegativity and total mass one are
construction fields, so downstream definitions cannot silently accept
arbitrary weight vectors as probability laws.
-/

namespace FreeEnergyPrinciple

open Finset
open scoped BigOperators

/-- A probability law on a finite type, represented by normalized real mass. -/
structure FiniteLaw (α : Type*) [Fintype α] where
  mass : α → ℝ
  nonneg : ∀ x, 0 ≤ mass x
  sum_one : ∑ x, mass x = 1

namespace FiniteLaw

variable {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]

instance : CoeFun (FiniteLaw α) (fun _ => α → ℝ) := ⟨FiniteLaw.mass⟩

@[simp]
theorem coe_mass (p : FiniteLaw α) (x : α) : p x = p.mass x := rfl

/-- Finite laws are equal when their mass functions are equal. -/
@[ext]
theorem ext_mass {p q : FiniteLaw α} (h : p.mass = q.mass) : p = q := by
  cases p
  cases q
  cases h
  rfl

/-- Every atom of a finite law lies in the unit interval. -/
theorem mass_le_one (p : FiniteLaw α) (x : α) : p x ≤ 1 := by
  classical
  calc
    p x ≤ ∑ y : α, p y :=
      Finset.single_le_sum (fun y _ => p.nonneg y) (Finset.mem_univ x)
    _ = 1 := p.sum_one

/-- Second marginal of a finite joint law. -/
def sndMarginal (p : FiniteLaw (α × β)) : FiniteLaw β where
  mass y := ∑ x : α, p (x, y)
  nonneg y := Finset.sum_nonneg fun x _ => p.nonneg (x, y)
  sum_one := by
    rw [Finset.sum_comm]
    simpa [Fintype.sum_prod_type] using p.sum_one

end FiniteLaw

/-- A normalized finite Markov kernel. -/
structure FiniteKernel (α β : Type*) [Fintype α] [Fintype β] where
  mass : α → β → ℝ
  nonneg : ∀ x y, 0 ≤ mass x y
  sum_one : ∀ x, ∑ y, mass x y = 1

namespace FiniteKernel

variable {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]

instance : CoeFun (FiniteKernel α β) (fun _ => α → β → ℝ) :=
  ⟨FiniteKernel.mass⟩

/-- Finite kernels are equal when their mass functions are equal. -/
@[ext]
theorem ext_mass {kernel₁ kernel₂ : FiniteKernel α β}
    (h : kernel₁.mass = kernel₂.mass) : kernel₁ = kernel₂ := by
  cases kernel₁
  cases kernel₂
  cases h
  rfl

/-- Each input of a normalized kernel indexes a finite output law. -/
def row (kernel : FiniteKernel α β) (x : α) : FiniteLaw β where
  mass y := kernel x y
  nonneg y := kernel.nonneg x y
  sum_one := kernel.sum_one x

/-- Joint law generated by a prior and a normalized finite kernel. -/
def joint (prior : FiniteLaw α) (kernel : FiniteKernel α β) :
    FiniteLaw (α × β) where
  mass xy := prior xy.1 * kernel xy.1 xy.2
  nonneg xy := mul_nonneg (prior.nonneg xy.1) (kernel.nonneg xy.1 xy.2)
  sum_one := by
    classical
    rw [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, kernel.sum_one, mul_one]
    exact prior.sum_one

/-- Predictive output law obtained by marginalizing a prior-kernel joint. -/
def predictive (prior : FiniteLaw α) (kernel : FiniteKernel α β) : FiniteLaw β :=
  (joint prior kernel).sndMarginal

@[simp]
theorem predictive_mass (prior : FiniteLaw α) (kernel : FiniteKernel α β)
    (y : β) :
    predictive prior kernel y = ∑ x : α, prior x * kernel x y := rfl

/-- Exact finite Bayes posterior at evidence with positive predictive mass. -/
noncomputable def posterior (prior : FiniteLaw α) (kernel : FiniteKernel α β)
    (y : β) (hy : 0 < predictive prior kernel y) : FiniteLaw α where
  mass x := prior x * kernel x y / predictive prior kernel y
  nonneg x := div_nonneg (mul_nonneg (prior.nonneg x) (kernel.nonneg x y)) hy.le
  sum_one := by
    rw [← Finset.sum_div]
    exact div_self (ne_of_gt hy)

/-- Bayes reconstruction: posterior mass times evidence equals joint mass. -/
theorem posterior_mul_predictive (prior : FiniteLaw α)
    (kernel : FiniteKernel α β) (y : β)
    (hy : 0 < predictive prior kernel y) (x : α) :
    posterior prior kernel y hy x * predictive prior kernel y =
      prior x * kernel x y := by
  change
    (prior x * kernel x y / predictive prior kernel y) *
        predictive prior kernel y = _
  exact div_mul_cancel₀ _ (ne_of_gt hy)

end FiniteKernel

end FreeEnergyPrinciple
