import Mathlib

set_option autoImplicit false

namespace McFadden1974.QPTest

/-- McFadden (1974), pp. 113–114 (PDF 9–10), data preceding (16).
`Fin N` indexes at least one trial and `Fin (J n)` indexes their alternatives. Each trial has at
least two alternatives and at least one observed choice, as stated in the section.
Attributes use the Euclidean norm on `EuclideanSpace ℝ (Fin K)`. -/
structure ChoiceData (N K : ℕ) where
  positive_trials : 0 < N
  J : Fin N → ℕ
  z : (n : Fin N) → Fin (J n) → EuclideanSpace ℝ (Fin K)
  S : (n : Fin N) → Fin (J n) → ℕ
  two_le_J : ∀ n, 2 ≤ J n
  positive_repetitions : ∀ n, 0 < ∑ i, S n i

/-- McFadden (1974), p. 116 (PDF 12), Axiom 6's weighted difference vectors.
The weight is the observed count for the first alternative; every ordered pair,
including equal and unchosen alternatives, remains in the index set. -/
def ChoiceData.w {N K : ℕ} (d : ChoiceData N K)
    (n : Fin N) (i j : Fin (d.J n)) : EuclideanSpace ℝ (Fin K) :=
  (d.S n i : ℝ) • (d.z n j - d.z n i)

/-- McFadden (1974), p. 116 (PDF 12), Axiom 5 (Full Rank).
The differences have full linear span. This is equivalent to full rank of the
paper's rows `z_in - z̄_n`, since each trial's logit probabilities are positive
and sum to one; the equivalent form avoids a parameter-dependent matrix. -/
def ChoiceData.Axiom5 {N K : ℕ} (d : ChoiceData N K) : Prop :=
  ∀ γ : EuclideanSpace ℝ (Fin K),
    (∀ n i j, inner ℝ (d.z n j - d.z n i) γ = 0) → γ = 0

/-- McFadden (1974), p. 116 (PDF 12), Axiom 6.
The inequality covers all trials and all ordered pairs of alternatives. -/
def ChoiceData.Axiom6 {N K : ℕ} (d : ChoiceData N K) : Prop :=
  ∀ γ : EuclideanSpace ℝ (Fin K),
    (∀ n i j, inner ℝ (d.w n i j) γ ≤ 0) → γ = 0

/-- McFadden (1974), p. 117 (PDF 13), equation (22).
The set of vectors `y` feasible for the quadratic program; all coefficients,
including those of zero generators, obey `α_ijn ≥ 1`. -/
def ChoiceData.qpFeasible {N K : ℕ} (d : ChoiceData N K) :
    Set (EuclideanSpace ℝ (Fin K)) :=
  {y | ∃ α : (n : Fin N) → Fin (d.J n) → Fin (d.J n) → ℝ,
    (∀ n i j, 1 ≤ α n i j) ∧
      y = ∑ n, ∑ i, ∑ j, α n i j • d.w n i j}

/-- McFadden (1974), p. 117 (PDF 13), Lemma 4, proof: the convex cone `K`
generated by all weighted difference vectors. Finite nonnegative combinations
give an explicit set representation of that cone. -/
def ChoiceData.coneSet {N K : ℕ} (d : ChoiceData N K) :
    Set (EuclideanSpace ℝ (Fin K)) :=
  {y | ∃ α : (n : Fin N) → Fin (d.J n) → Fin (d.J n) → ℝ,
    (∀ n i j, 0 ≤ α n i j) ∧
      y = ∑ n, ∑ i, ∑ j, α n i j • d.w n i j}

end McFadden1974.QPTest
