import Mathlib

open MeasureTheory

namespace VectorPayoffs.Convex

/-- `σ(δ₁, …, δₙ)`: the σ-algebra generated by the first `n` terms of a real sequence of random
variables indexed from `1` (`δ 0` is unused). For `n = 0` it is the trivial σ-algebra. -/
def pastSigma {Ω : Type} (δ : ℕ → Ω → ℝ) (n : ℕ) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω (i : Fin n) => δ (i.val + 1) ω) inferInstance

/-- Blackwell (1956), §2, p. 4, conditions (5), (6), (7) on a sequence `δ₁, δ₂, …`:
(5) `E(δₙ | δ₁, …, δₙ₋₁) ≤ (1 - 2/n) δₙ₋₁ + c/n²` if `δₙ₋₁ > 0` (for `n ≥ 2`);
(6) `0 ≤ δₙ ≤ a` (for `n ≥ 1`);
(7) `|δₙ - δₙ₋₁| ≤ b/n` (for `n ≥ 2`);
(6) and (7) almost surely. -/
def SatisfiesRecursion {Ω : Type} [MeasurableSpace Ω] (a b c : ℝ) (μ : Measure Ω)
    (δ : ℕ → Ω → ℝ) : Prop :=
  (∀ n : ℕ, 2 ≤ n → ∀ᵐ ω ∂μ, 0 < δ (n - 1) ω →
      μ[δ n | pastSigma δ (n - 1)] ω ≤ (1 - 2 / (n : ℝ)) * δ (n - 1) ω + c / (n : ℝ) ^ 2) ∧
  (∀ n : ℕ, 1 ≤ n → ∀ᵐ ω ∂μ, 0 ≤ δ n ω ∧ δ n ω ≤ a) ∧
  (∀ n : ℕ, 2 ≤ n → ∀ᵐ ω ∂μ, |δ n ω - δ (n - 1) ω| ≤ b / (n : ℝ))

end VectorPayoffs.Convex
