import Mathlib

namespace StochasticOrders.Multivariate

open MeasureTheory

variable {Ω Ω' : Type*} [MeasurableSpace Ω] [MeasurableSpace Ω']

/-- The usual multivariate stochastic order `X ≤st Y` (Shaked & Shanthikumar, *Stochastic
Orders*, Springer 2007, p. 266, Eq. (6.B.4)): an `n`-dimensional random vector `X` on `(Ω, μ)` is
smaller than an `n`-dimensional random vector `Y` on a (possibly different) probability space
`(Ω', ν)` in the usual multivariate stochastic order if `E[φ(X)] ≤ E[φ(Y)]` for every increasing
function `φ : (Fin n → ℝ) → ℝ` (increasing with respect to the coordinatewise order on
`Fin n → ℝ`, i.e. Mathlib's `Pi` order) for which the two expectations exist.

Corrected version (`_v2`): the test functions `φ` are required to be Borel measurable, as the
book's "E[φ(X)]" tacitly requires (`φ(X)` must be a random variable). For `n ≥ 2` an increasing
function on `ℝⁿ` need not be Borel (the indicator of the upper set generated by a non-measurable
antichain is increasing), and for such `φ` the Bochner integral `∫ φ ∘ X` is not a function of the
law of `X`, so the previous definition was not a relation between distributions and the book's
Theorem 6.B.1 failed for it in both directions. -/
def MultivariateOrder {n : ℕ} (μ : Measure Ω) (ν : Measure Ω')
    (X : Ω → Fin n → ℝ) (Y : Ω' → Fin n → ℝ) : Prop :=
  ∀ φ : (Fin n → ℝ) → ℝ, Measurable φ → Monotone φ → Integrable (φ ∘ X) μ →
    Integrable (φ ∘ Y) ν → ∫ ω, φ (X ω) ∂μ ≤ ∫ ω, φ (Y ω) ∂ν

end StochasticOrders.Multivariate
