import Mathlib

namespace FoundationsML.MultiClass

/-- The pointwise-max family `G = {max{h_1,…,h_l} : h_i ∈ F_i, i ∈ [l]}` generated by `l ≥ 1`
hypothesis sets `F_1,…,F_l` in `ℝ^X` (Mohri, Rostamizadeh & Talwalkar, *Foundations of Machine
Learning*, 2nd ed., MIT Press 2018, Lemma 9.1, p. 216, PDF p. 233).

**Formalization Note.** The index set `ι` (standing for `[l]`) is a `Fintype` with a
`Nonempty` instance, matching `l ≥ 1`; `⨆ j, h j x` is the real supremum over the finite
nonempty index type `ι`, equal to the actual maximum `max{h_1(x),…,h_l(x)}` for the
`Fintype`/`Nonempty` case this definition is always used with. -/
noncomputable def MaxFamily {X ι : Type*} [Fintype ι] [Nonempty ι]
    (F : ι → Set (X → ℝ)) : Set (X → ℝ) :=
  {g | ∃ h : ι → (X → ℝ), (∀ j, h j ∈ F j) ∧ g = fun x => ⨆ j, h j x}

end FoundationsML.MultiClass
