import Mathlib
import Definitions.Def_DiscountedDP_Stationary_Model

namespace DiscountedDP.Stationary

open MeasureTheory ProbabilityTheory

variable {S A : Type*} [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    [MeasurableSpace A] [StandardBorelSpace A] [Nonempty A]

/-- The transition kernel from a history and the chosen action to the next state. -/
noncomputable def nextKernel (P : Problem S A) (n : ℕ) :
    Kernel (Hist S A n × A) S :=
  P.q ∘ₖ Kernel.deterministic (fun ha : Hist S A n × A => (ha.1.2, ha.2))
    (by fun_prop)

/-- The law of the history before the `(n+1)`-st decision, conditional on `s`. -/
noncomputable def historyLaw (P : Problem S A) (π : Plan (S := S) (A := A)) (s : S) :
    (n : ℕ) → Measure (Hist S A n)
  | 0 => Measure.dirac ((fun i : Fin 0 => Fin.elim0 i), s)
  | n + 1 =>
      letI : IsMarkovKernel (π.κ n) := π.κ_markov n
      letI : IsMarkovKernel P.q := P.q_markov
      have happend : Measurable
          (fun x : (Hist S A n × A) × S =>
            ((MeasurableEquiv.piFinSuccAbove (fun _ : Fin (n + 1) => S × A)
                (Fin.last n)).symm ((x.1.1.2, x.1.2), x.1.1.1), x.2)) := by
        fun_prop
      (Measure.compProd (Measure.compProd (historyLaw P π s n) (π.κ n))
        (nextKernel P n)).map
        (fun x =>
          ((MeasurableEquiv.piFinSuccAbove (fun _ : Fin (n + 1) => S × A)
            (Fin.last n)).symm ((x.1.1.2, x.1.2), x.1.1.1), x.2))

/-- Law of the current history, chosen action, and next state at stage `n`. -/
noncomputable def stageLaw (P : Problem S A) (π : Plan (S := S) (A := A))
    (s : S) (n : ℕ) : Measure ((Hist S A n × A) × S) := by
  letI : IsMarkovKernel (π.κ n) := π.κ_markov n
  letI : IsMarkovKernel P.q := P.q_markov
  exact Measure.compProd (Measure.compProd (historyLaw P π s n) (π.κ n))
    (nextKernel P n)

/-- The expectation of the one-stage reward at stage `n`, starting from `s`. -/
noncomputable def stageReward (P : Problem S A) (π : Plan (S := S) (A := A))
    (s : S) (n : ℕ) : ℝ :=
  ∫ x, P.r (x.1.1.2, x.1.2, x.2) ∂stageLaw P π s n

/-- Blackwell's return `I(π)(s) = ∑ₙ βⁿ Eₛ[r(σₙ,αₙ,σₙ₊₁)]` (Section 3, p. 228).
The series is absolutely convergent: each stage law is a probability measure,
the reward is bounded, and `0 ≤ β < 1`. -/
noncomputable def I (P : Problem S A) (π : Plan (S := S) (A := A)) (s : S) : ℝ :=
  ∑' n : ℕ, P.β ^ n * stageReward P π s n

/-- The randomized plan associated to a non-randomized Markov plan. -/
noncomputable def MarkovPlan.toPlan (π : MarkovPlan S A) : Plan (S := S) (A := A) where
  κ n := Kernel.deterministic (fun h : Hist S A n => (π n).1 h.2)
    ((π n).2.comp measurable_snd)
  κ_markov n := by infer_instance

/-- The stationary plan generated by a measurable decision rule. -/
def stationary (f : {g : S → A // Measurable g}) : MarkovPlan S A := fun _ => f

/-- Prefix a Markov plan by one measurable decision rule. -/
def MarkovPlan.cons (f : {g : S → A // Measurable g}) (π : MarkovPlan S A) :
    MarkovPlan S A :=
  fun n => if n = 0 then f else π (n - 1)

/-- `(p, ε)`-optimality, Section 3, p. 229. -/
def IsPOptimal (P : Problem S A) (p : Measure S) (ε : ℝ)
    (πstar : Plan (S := S) (A := A)) : Prop :=
  ∀ π : Plan (S := S) (A := A), p {s | I P πstar s + ε < I P π s} = 0

/-- Pointwise `ε`-optimality against all randomized history-dependent plans. -/
def IsEOptimal (P : Problem S A) (ε : ℝ)
    (πstar : Plan (S := S) (A := A)) : Prop :=
  ∀ π : Plan (S := S) (A := A), ∀ s, I P π s ≤ I P πstar s + ε

/-- Exact optimality against all randomized history-dependent plans. -/
def IsOptimal (P : Problem S A) (πstar : Plan (S := S) (A := A)) : Prop :=
  ∀ π : Plan (S := S) (A := A), ∀ s, I P π s ≤ I P πstar s

/-- Pointwise supremum of returns over every plan. -/
noncomputable def optReturn (P : Problem S A) (s : S) : ℝ :=
  ⨆ π : Plan (S := S) (A := A), I P π s

end DiscountedDP.Stationary
