import Mathlib

namespace KannanLattice.Core

open InnerProductSpace

/-- The integer point of `ℝⁿ` (as `EuclideanSpace ℝ (Fin n)`) with integer coordinates `z`
(Kannan 1987, Notation p. 4: `Zⁿ` is the set of `n`-vectors with integer components). -/
noncomputable def intPt {n : ℕ} (z : Fin n → ℤ) : EuclideanSpace ℝ (Fin n) :=
  WithLp.toLp 2 (fun i => (z i : ℝ))

/-- The lattice `L(b₁, …, b_m)` generated by a family `b` of vectors in `ℝᵏ`: the set of all
integer linear combinations of the `b_j` (Notation p. 4, §1 p. 5). It is a lattice in the paper's
sense when `b` is linearly independent over `ℝ`. -/
def lattice {m k : ℕ} (b : Fin m → EuclideanSpace ℝ (Fin k)) :
    Submodule ℤ (EuclideanSpace ℝ (Fin k)) :=
  Submodule.span ℤ (Set.range b)

/-- The paper's `b_j(j) = |b_j*|` ((1.7), p. 6): the length of the `j`-th Gram–Schmidt vector.
Indices are 0-based: `gsLen b j` is the paper's `b_{j+1}(j+1)`. -/
noncomputable def gsLen {m k : ℕ} (b : Fin m → EuclideanSpace ℝ (Fin k)) (j : Fin m) : ℝ :=
  ‖gramSchmidt ℝ b j‖

/-- The paper's Gram–Schmidt coefficient `b_i(j) = (b_i, u_j)` with `u_j = b_j*/|b_j*|`
((1.2)–(1.7), pp. 5–6), so that `b_i = Σ_j b_i(j) u_j`. 0-based: `gsCoeff b i j` is the paper's
`b_{i+1}(j+1)`. One has `gsCoeff b j j = gsLen b j` and `gsCoeff b i j = 0` for `j > i`. -/
noncomputable def gsCoeff {m k : ℕ} (b : Fin m → EuclideanSpace ℝ (Fin k)) (i j : Fin m) : ℝ :=
  inner ℝ (b i) (gramSchmidtNormed ℝ b j)

/-- The determinant `d(L(b₁, …, b_m))` (p. 6): the product of the lengths of the Gram–Schmidt
vectors `b_t*` (equivalently, the absolute value of the determinant of the lower triangular
`m × m` matrix of the `b_i(j)`). This is meaningful also when `m < k`. -/
noncomputable def latticeDet {m k : ℕ} (b : Fin m → EuclideanSpace ℝ (Fin k)) : ℝ :=
  ∏ j, gsLen b j

/-- `Λ₁(S)`: the length of a shortest nonzero vector of `S` (Notation p. 4), as the infimum of the
norms of the nonzero elements. It is only used for nonzero lattices, where the infimum is attained
and positive; on `{0}` it is the junk value `0`. -/
noncomputable def lambdaOne {k : ℕ} (S : Set (EuclideanSpace ℝ (Fin k))) : ℝ :=
  sInf ((fun v => ‖v‖) '' (S \ {0}))

/-- The orthogonal projection of `ℝᵏ` onto the orthogonal complement of
`span_ℝ {b_i : i < j}` (0-based `j`; the span of the empty family is `{0}`, so `projOrth b 0` is
the identity). -/
noncomputable def projOrth {m k : ℕ} (b : Fin m → EuclideanSpace ℝ (Fin k)) (j : Fin m) :
    EuclideanSpace ℝ (Fin k) →L[ℝ] EuclideanSpace ℝ (Fin k) :=
  (Submodule.span ℝ (b '' Set.Iio j))ᗮ.starProjection

/-- The projected lattice `L_j(b₁, …, b_m)` (Notation p. 4): the projection of `L(b)` orthogonal to
the span of `b₁, …, b_{j−1}`. 0-based: `projLattice b j` is the paper's `L_{j+1}`, and
`projLattice b 0 = L(b)`. It depends on the basis, not only on the lattice. -/
noncomputable def projLattice {m k : ℕ} (b : Fin m → EuclideanSpace ℝ (Fin k)) (j : Fin m) :
    Set (EuclideanSpace ℝ (Fin k)) :=
  projOrth b j '' (lattice b : Set (EuclideanSpace ℝ (Fin k)))

end KannanLattice.Core
