import Mathlib

namespace NetworkControl.UtilityFairness

open MeasureTheory

/-- The one-step Lyapunov drift `∆(U(t)) := E{L(U(t+1)) - L(U(t)) | U(t)}`, p. 81, restated
locally in this chunk's own sub-namespace (drafts cannot import chunk `04-backpressure`'s copy).
`L` is any nonnegative function of the backlog vector `U : Fin N → ℝ`; the conditioning is on the
σ-algebra generated by the current backlog `U(t)`, exactly as in Chapter 4. -/
noncomputable def drift {Ω : Type*} [mΩ : MeasurableSpace Ω] (P : Measure Ω)
    {N : ℕ} (L : (Fin N → ℝ) → ℝ) (U : ℕ → Ω → Fin N → ℝ) (t : ℕ) : Ω → ℝ :=
  P[(fun ω => L (U (t + 1) ω) - L (U t ω)) | MeasurableSpace.comap (U t) inferInstance]

end NetworkControl.UtilityFairness
