import Mathlib
import Definitions.Def_StochasticProg_Recourse_Instance
import Definitions.Def_StochasticProg_LShaped_Bases

namespace MulticutLShaped.Bound

open StochasticProg.Recourse StochasticProg.LShaped
open scoped Matrix

variable {n1 n2 m1 m2 K : ℕ}

/-- A simplex-optimal basis of Problem `k` of type (7) at the first-stage point `x`
(Birge–Louveaux 1988, p. 386): `min q_k y` s.t. `W y = h_k − T_k x`, `y ≥ 0`.
The basic submatrix `W_b` is invertible, the basic solution `W_b⁻¹ (h_k − T_k x)` is
nonnegative (primal feasible), and the simplex multiplier `π = q_b W_b⁻¹` satisfies
`π W ≤ q_k` componentwise (all reduced costs nonnegative: dual feasible). This is the
optimality certificate with which the simplex method terminates. -/
def IsSimplexOptimal (inst : Instance n1 n2 m1 m2 K) (k : Fin K) (b : Basis n2 m2)
    (x : Fin n1 → ℝ) : Prop :=
  IsUnit (inst.W.submatrix id b.1).det ∧
  (∀ j, 0 ≤ ((inst.W.submatrix id b.1)⁻¹ *ᵥ (inst.h k - inst.T k *ᵥ x)) j) ∧
  (∀ j, (multiplier inst b (inst.q k) ᵥ* inst.W) j ≤ inst.q k j)

/-- A simplex-optimal basis of the Step 2 feasibility LP at `x` for scenario `k`
(p. 386): `min e v⁺ + e v⁻` s.t. `W y + I v⁺ − I v⁻ = h_k − T_k x`, `y, v⁺, v⁻ ≥ 0`.
The basic submatrix of `[W | I | −I]` is invertible, the basic solution is nonnegative,
and the multiplier `σ` satisfies `σ [W | I | −I] ≤ (0, e, e)` componentwise, i.e.
`σ W ≤ 0` and `−1 ≤ σ_i ≤ 1`. -/
def IsFeasSimplexOptimal (inst : Instance n1 n2 m1 m2 K) (k : Fin K) (b : FeasBasis n2 m2)
    (x : Fin n1 → ℝ) : Prop :=
  IsUnit ((feasMatrix inst).submatrix id b.1).det ∧
  (∀ j, 0 ≤ (((feasMatrix inst).submatrix id b.1)⁻¹ *ᵥ (inst.h k - inst.T k *ᵥ x)) j) ∧
  (∀ c, (feasMultiplier inst b ᵥ* feasMatrix inst) c ≤ feasCost c)

/-- The optimality cut (15)–(16) of scenario `k` generated by the basis `b` (p. 387):
`(E, e) = (p_k π T_k, p_k π h_k)` with `π` the simplex multiplier of `b` for cost `q_k`.
The cut reads `E x + θ_k ≥ e`. -/
noncomputable def optCut (inst : Instance n1 n2 m1 m2 K) (k : Fin K) (b : Basis n2 m2) :
    (Fin n1 → ℝ) × ℝ :=
  (inst.p k • (multiplier inst b (inst.q k) ᵥ* inst.T k),
   inst.p k * (multiplier inst b (inst.q k) ⬝ᵥ inst.h k))

open Classical in
/-- The finite set of all optimality cuts (15)–(16) that Step 3 can generate for scenario
`k`: the cuts `optCut inst k b` of bases `b` that are simplex-optimal for Problem `k` of
type (7) at some first-stage point `x ∈ K₁`. It is a `Finset` because there are finitely
many bases. -/
noncomputable def cutSet (inst : Instance n1 n2 m1 m2 K) (k : Fin K) :
    Finset ((Fin n1 → ℝ) × ℝ) :=
  (Finset.univ.filter (fun b : Basis n2 m2 => ∃ x ∈ K1 inst, IsSimplexOptimal inst k b x)).image
    (optCut inst k)

end MulticutLShaped.Bound
