import Mathlib
import Definitions.Def_CubicNewton_LocalQuad_IsRelaxedRun
import Definitions.Def_CubicNewton_LocalQuad_deltaMeasure

namespace CubicNewton.LocalQuad

/-- Nesterov–Polyak 2006, Theorem 3, item 2, (3.7), p. 187, in the case `F = ℝⁿ`:
let `f″(x₀) ≻ 0` and `δ₀ ≤ 1/4`, and let `{x_k}` be generated by the relaxed method (3.5).
Then for every `k ≥ 0`, `e⁻¹ λₙ(f″(x₀)) ≤ λₙ(f″(x_k)) ≤ e^{3/4} λₙ(f″(x₀))`. -/
theorem theorem3_eigenvalue_bounds {n : ℕ}
    (f : EuclideanSpace ℝ (Fin n) → ℝ)
    (g : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n))
    (H : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n) →L[ℝ] EuclideanSpace ℝ (Fin n))
    (L : ℝ)
    (hf : ∀ x, HasGradientAt f (g x) x) (hg : ∀ x, HasFDerivAt g (H x) x)
    (hL : 0 < L) (hLip : ∀ x y, ‖H x - H y‖ ≤ L * ‖x - y‖)
    (hn : 0 < n) (x : ℕ → EuclideanSpace ℝ (Fin n)) (M : ℕ → ℝ)
    (hrun : IsRelaxedRun L g H x M)
    (hpos : 0 < CubicNewton.Shared.lamMin (H (x 0))) (hδ0 : deltaMeasure L g H (x 0) ≤ 1 / 4) :
    ∀ k, Real.exp (-1) * CubicNewton.Shared.lamMin (H (x 0)) ≤ CubicNewton.Shared.lamMin (H (x k)) ∧
      CubicNewton.Shared.lamMin (H (x k)) ≤ Real.exp (3 / 4) * CubicNewton.Shared.lamMin (H (x 0)) := by sorry

end CubicNewton.LocalQuad
