import Mathlib
import Definitions.Def_NetworkControl_Backpressure_StronglyStable
import Definitions.Def_NetworkControl_Backpressure_lyapunovL

namespace NetworkControl.Backpressure

open MeasureTheory

/-- Lemma 4.1 (Lyapunov Stability), p. 50. If there exist constants `B > 0`, `ε > 0` such that at
every timeslot `t`, the conditional expected drift of `L(U(t))` given the current backlog vector
`U(t)` satisfies `E{L(U(t+1)) - L(U(t)) | U(t)} ≤ B - ε Σ_i U_i(t)`, then the network is strongly
stable, and the average congestion satisfies `limsup_{t→∞} (1/t) Σ_τ Σ_i E{U_i(τ)} ≤ B/ε`.

**Formalization note.** The `limsup ≤ B/ε` conclusion is stated in the equivalent quantifier-light
form `∀ t, (1/t) Σ_{τ<t} Σ_i E{U_i(τ)} ≤ B/ε`, matching the standard telescoping proof of this
lemma, which bounds the Cesàro average for every `t` (not merely asymptotically) — the same
convention as `03-capacity-region`'s `StronglyStable`. Conditioning "given `U(t)`" is modeled via
`condExp` on the σ-algebra generated by `U(t)` (`MeasurableSpace.comap (U t) inferInstance`).
Explicit `Integrable`/`Measurable` guards prevent `condExp`/`∫` silently defaulting to `0`. -/
theorem lemma_lyapunov_stability
    {Ω : Type*} [mΩ : MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    {L : ℕ} (U : ℕ → Ω → Fin L → ℝ) (B ε : ℝ) (hB : 0 < B) (hε : 0 < ε)
    (hMeas : ∀ t : ℕ, ∀ i : Fin L, Measurable (fun ω => U t ω i))
    (hIntegU : ∀ t : ℕ, ∀ i : Fin L, Integrable (fun ω => U t ω i) P)
    (hIntegDrift : ∀ t : ℕ, Integrable (fun ω => lyapunovL (U (t + 1) ω) - lyapunovL (U t ω)) P)
    (hdrift : ∀ t : ℕ,
      (P[(fun ω => lyapunovL (U (t + 1) ω) - lyapunovL (U t ω))
          | MeasurableSpace.comap (U t) inferInstance])
        ≤ᵐ[P] (fun ω => B - ε * ∑ i : Fin L, U t ω i)) :
    NetworkStronglyStable (fun i t => ∫ ω, U t ω i ∂P) ∧
      ∀ t : ℕ, (1 / (t : ℝ)) * ∑ τ ∈ Finset.range t, ∑ i : Fin L, ∫ ω, U τ ω i ∂P ≤ B / ε := by sorry

end NetworkControl.Backpressure
