import Mathlib
import Definitions.Def_GoldenRatioVI_Fixed_solutionSet
import Definitions.Def_GoldenRatioVI_Fixed_IsGRAALRun
open scoped goldenRatio

namespace GoldenRatioVI.Fixed

/-- Theorem 1: let `F` be `L`-Lipschitz on `dom g` and let (C1)–(C3) hold. For arbitrary
`z¹, z̄⁰ ∈ E` and `λ ∈ (0, φ/(2L)]`, the sequences `(zᵏ)`, `(z̄ᵏ)` generated by the Golden
Ratio Algorithm (6) converge to a common solution of the variational inequality (1). -/
theorem graal_converges {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] (g : E → EReal) (F : E → E) (L lam : ℝ) (z zbar : ℕ → E)
    (hS : (solutionSet g F).Nonempty)
    (hg : IsProperConvexLSC g) (hF : IsMonotoneOperatorOn F (effDom g))
    (hL : 0 < L) (hLip : ∀ u ∈ effDom g, ∀ v ∈ effDom g, ‖F u - F v‖ ≤ L * ‖u - v‖)
    (hlam : 0 < lam) (hlamL : lam ≤ φ / (2 * L))
    (hrun : IsGRAALRun g F lam z zbar) :
    ∃ zs ∈ solutionSet g F,
      Filter.Tendsto z Filter.atTop (nhds zs) ∧
        Filter.Tendsto zbar Filter.atTop (nhds zs) := by sorry

end GoldenRatioVI.Fixed

