import Mathlib

namespace FirstOrderOpt.Deterministic

/-- Theorem 3.6, general recursion (3.3.16). `(x t, xTilde t, xBar t)` are generated by the
accelerated gradient method (3.3.4)-(3.3.6) with `μ = 0`. If `α t = q t` (3.3.13),
`L·α t ≤ 1/γ t` (3.3.14) for every `t ∈ [1,k]`, and `γ t (1-α t)/α t ≤ γ(t-1)/α(t-1)` (3.3.15)
for every `t ∈ [2,k]`, then
`f(xBar k) - f(x*) + (α k/γ k)V(x k,x*) ≤ (α k γ 1 (1-α 1))/(γ k α 1)[f(xBar 0)-f(x*)] +
(α k/γ k)V(x 0,x*)`.

**Formalization note.** Condition (3.3.15) is stated for `t = 2,…,k`, not `t = 1,…,k` as the
book's own phrasing reads: the book's proof only ever invokes it for `t ≥ 2` (the `t=1` step of
the telescoping sum is Proposition 3.1's raw one-step inequality connecting `t=1` directly to the
`t=0` base data, never (3.3.15) at `t=1`, which would need an undefined `γ 0 / α 0`). See
`STATUS.md`. `V` is pinned down to a genuine Bregman divergence (nonnegative, three-point
identity (3.2.6) via `dV`), since this theorem's proof is Proposition 3.1's one-step recursion
(`accelerated_one_step_recursion`) telescoped over `t`, and needs the same structure at every
step. -/
theorem accelerated_gradient_recursion_bound {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (X : Set E) (f : E → ℝ) (V : E → E → ℝ) (dV : E → E → E →L[ℝ] ℝ) (L : ℝ) (hL : 0 < L)
    (fGrad : E → E →L[ℝ] ℝ)
    (hSmooth : ∀ x ∈ X, ∀ y ∈ X, f y - f x - (fGrad x) (y - x) ≤ (L / 2) * ‖y - x‖ ^ 2)
    (hVnonneg : ∀ x ∈ X, ∀ z ∈ X, 0 ≤ V x z)
    (hVthreepoint : ∀ x ∈ X, ∀ y ∈ X, ∀ z ∈ X, V x z = V x y + (dV x y) (z - y) + V y z)
    (x xTilde xBar : ℕ → E) (q γ α : ℕ → ℝ)
    (hx : ∀ t, x t ∈ X) (hxBar : ∀ t, xBar t ∈ X) (hxTilde : ∀ t, 1 ≤ t → xTilde t ∈ X)
    (k : ℕ) (hk : 1 ≤ k)
    (hγpos : ∀ t, 1 ≤ t → t ≤ k → 0 < γ t) (hαpos : ∀ t, 1 ≤ t → t ≤ k → 0 < α t)
    (hTildeDef : ∀ t, 1 ≤ t → t ≤ k → xTilde t = (1 - q t) • xBar (t - 1) + (q t) • x (t - 1))
    (hxDef : ∀ t, 1 ≤ t → t ≤ k → ∀ y ∈ X,
      γ t * (fGrad (xTilde t)) (x t) + V (x (t - 1)) (x t) ≤
        γ t * (fGrad (xTilde t)) y + V (x (t - 1)) y)
    (hBarDef : ∀ t, 1 ≤ t → t ≤ k → xBar t = (1 - α t) • xBar (t - 1) + (α t) • x t)
    (h13 : ∀ t, 1 ≤ t → t ≤ k → α t = q t)
    (h14 : ∀ t, 1 ≤ t → t ≤ k → L * α t ≤ 1 / γ t)
    (h15 : ∀ t, 2 ≤ t → t ≤ k → γ t * (1 - α t) / α t ≤ γ (t - 1) / α (t - 1))
    (xstar : E) (hxstar : xstar ∈ X) (hxstar_opt : ∀ y ∈ X, f xstar ≤ f y) :
    f (xBar k) - f xstar + (α k / γ k) * V (x k) xstar ≤
      (α k * γ 1 * (1 - α 1) / (γ k * α 1)) * (f (xBar 0) - f xstar) +
        (α k / γ k) * V (x 0) xstar := by sorry

end FirstOrderOpt.Deterministic
