import Mathlib

namespace FirstOrderOpt.Deterministic

open scoped RealInnerProductSpace

/-- Theorem 3.1 (subgradient descent function-value bound). `f` is `M`-Lipschitz on `X`
(Assumption (3.1.5)); `x t` is generated by the projected-subgradient update (3.1.3), with `g t`
a subgradient of `f` at `x t`. Then for every `x' ∈ X` and `s ≤ k`,
`Σ_{t=s}^{k} γt[f(x t) - f x'] ≤ (1/2)(‖x' - x s‖² + M² Σ_{t=s}^{k} γt²)`. -/
theorem subgradient_descent_bound {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (X : Set E) (f : E → ℝ) (M : ℝ) (hM : 0 < M)
    (hLip : ∀ x ∈ X, ∀ y ∈ X, |f x - f y| ≤ M * ‖x - y‖)
    (x g : ℕ → E) (γ : ℕ → ℝ)
    (hx : ∀ t, x t ∈ X) (hγ : ∀ t, 0 < γ t)
    (hsub : ∀ t, ∀ y ∈ X, f (x t) + ⟪g t, y - x t⟫ ≤ f y)
    (hmin : ∀ t, ∀ y ∈ X, γ t * ⟪g t, x (t + 1)⟫ + (1 / 2) * ‖x (t + 1) - x t‖ ^ 2 ≤
      γ t * ⟪g t, y⟫ + (1 / 2) * ‖y - x t‖ ^ 2)
    (s k : ℕ) (hsk : s ≤ k) :
    ∀ x' ∈ X, ∑ t ∈ Finset.Icc s k, γ t * (f (x t) - f x') ≤
      (1 / 2) * (‖x' - x s‖ ^ 2 + M ^ 2 * ∑ t ∈ Finset.Icc s k, (γ t) ^ 2) := by sorry

end FirstOrderOpt.Deterministic
