import Mathlib
import Definitions.Def_CubicNewton_Shared_IsCubicNewtonRun
import Definitions.Def_CubicNewton_StarConvex_IsStarConvexFn

namespace CubicNewton.StarConvex

/-- Nesterov–Polyak 2006, Theorem 4, item 2, inequality (4.2), p. 189. Standing assumptions of
Section 2: `F` closed and convex, `x₀ ∈ int F`, the level set `{x : f(x) ≤ f(x₀)}` lies in
`int F`, `f` twice differentiable on `F` (gradient `g`, Hessian `H`), Assumption 1 (Hessian
`L`-Lipschitz on `F`, `L > 0`), and `0 < L₀ ≤ L`. Assume `f` is star-convex (Definition 1) and `F`
is bounded, with `D = diam F`. Let `x₀, x₁, …` be generated by method (3.3) and let `x*` be a
global minimizer of `f`, `f* = f(x*)`. If `f(x₀) − f* ≤ (3/2) L D³`, then for all `k ≥ 0`,
`f(x_k) − f(x*) ≤ 3 L D³ / (2 (1 + k/3)²)`. -/
theorem star_convex_rate {n : ℕ}
    (F : Set (EuclideanSpace ℝ (Fin n))) (f : EuclideanSpace ℝ (Fin n) → ℝ)
    (g : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n))
    (H : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n) →L[ℝ] EuclideanSpace ℝ (Fin n))
    (L L₀ : ℝ) (x₀ : EuclideanSpace ℝ (Fin n))
    (hF_closed : IsClosed F) (hF_convex : Convex ℝ F)
    (hx₀ : x₀ ∈ interior F) (hlevel : {x | f x ≤ f x₀} ⊆ interior F)
    (hf : ∀ x ∈ F, HasGradientAt f (g x) x) (hg : ∀ x ∈ F, HasFDerivAt g (H x) x)
    (hL : 0 < L) (hLip : ∀ x ∈ F, ∀ y ∈ F, ‖H x - H y‖ ≤ L * ‖x - y‖)
    (hL₀ : 0 < L₀) (hL₀L : L₀ ≤ L)
    (hstar : IsStarConvexFn F f) (hF_bdd : Bornology.IsBounded F)
    (x : ℕ → EuclideanSpace ℝ (Fin n)) (M : ℕ → ℝ)
    (hrun : CubicNewton.Shared.IsCubicNewtonRun f g H L₀ L x₀ x M)
    (xs : EuclideanSpace ℝ (Fin n)) (hxs : ∀ y, f xs ≤ f y)
    (h0 : f x₀ - f xs ≤ 3 / 2 * L * Metric.diam F ^ 3) :
    ∀ k : ℕ, f (x k) - f xs ≤
      3 * L * Metric.diam F ^ 3 / (2 * (1 + 1 / 3 * (k : ℝ)) ^ 2) := by sorry

end CubicNewton.StarConvex

