import Mathlib

namespace FirstOrderOpt.ProjectionFree

/-- Theorem 7.1 (goal theorem) — classic conditional gradient (Frank-Wolfe) method's convergence
rate. `X` is a nonempty compact convex subset of a normed space `E`; `f` is `L`-smooth on `X` in
the sense of (7.1.4): its gradient selector `fGrad` is `L`-Lipschitz in operator norm. `x k` is
generated by Algorithm 7.1's exact linear-optimization (LO) oracle at `y (k-1)`
(`x k ∈ Argmin_{z∈X}⟨f'(y(k-1)),z⟩`), and `y k = (1-α k) • y (k-1) + α k • x k` for some
`α k ∈ [0,1]`. `hyk_le` packages both stepsize policies (7.1.9) (the fixed schedule `α_k=2/(k+1)`)
and (7.1.10) (exact line search): under either, `f(y k) ≤ f(ỹ k)` for `ỹ k` the point the *fixed*
schedule `2/(k+1)` would have produced — trivially by equality under (7.1.9), or because `y k`
optimizes `f` over the whole segment under (7.1.10) and `ỹ k` is one point on that segment. This
is exactly the step the book's own proof of Theorem 7.1 uses to treat both policies at once (see
`STATUS.md`). `hcvx` states the convexity of `f` used in the book's proof (PDF p. 434), added
2026-09-19. -/
theorem conditional_gradient_rate {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (X : Set E) (hXconv : Convex ℝ X) (hXcompact : IsCompact X)
    (f : E → ℝ) (fGrad : E → E →L[ℝ] ℝ) (L : ℝ) (hL : 0 < L)
    (hSmooth : ∀ x ∈ X, ∀ y ∈ X, ‖fGrad x - fGrad y‖ ≤ L * ‖x - y‖)
    (hcvx : ∀ x ∈ X, ∀ z ∈ X, f x + (fGrad x) (z - x) ≤ f z)
    (x y : ℕ → E) (hx0 : x 0 ∈ X) (hy0 : y 0 = x 0)
    (hx : ∀ k, 1 ≤ k → x k ∈ X) (hy : ∀ k, y k ∈ X)
    (hLO : ∀ k, 1 ≤ k → ∀ z ∈ X, (fGrad (y (k - 1))) (x k) ≤ (fGrad (y (k - 1))) z)
    (α : ℕ → ℝ) (hα : ∀ k, 1 ≤ k → α k ∈ Set.Icc (0 : ℝ) 1)
    (hyDef : ∀ k, 1 ≤ k → y k = (1 - α k) • y (k - 1) + (α k) • x k)
    (hyk_le : ∀ k, 1 ≤ k →
      f (y k) ≤ f ((1 - 2 / ((k : ℝ) + 1)) • y (k - 1) + (2 / ((k : ℝ) + 1)) • x k))
    (xstar : E) (hxstar : xstar ∈ X) (hxstar_opt : ∀ z ∈ X, f xstar ≤ f z)
    (k : ℕ) (hk : 1 ≤ k) :
    f (y k) - f xstar ≤ (2 * L / ((k : ℝ) * ((k : ℝ) + 1))) *
      ∑ i ∈ Finset.Icc 1 k, ‖x i - y (i - 1)‖ ^ 2 := by sorry

end FirstOrderOpt.ProjectionFree

