import Mathlib
import Definitions.Def_HeldWolfeCrowder_CoreProblem_Setting

namespace HeldWolfeCrowder.CoreProblem

open scoped InnerProductSpace
open Filter Topology

/-- **Held, Wolfe & Crowder (1974), Lemma 6.2, p. 82.** Under the standing assumptions of §6
(`w` bounded above; `{π^j}` generated by (2.6) with positive step sizes satisfying (2.7)) and
`{π^j}` bounded: for any `J` there exists `J* > J` such that the core problem `P(J, J*)` is
feasible. -/
theorem core_problem_feasible {n : ℕ} {ι : Type*} [Fintype ι] [Nonempty ι]
    (c : ι → ℝ) (v : ι → EuclideanSpace ℝ (Fin n)) (hw : BddAbove (Set.range (w c v)))
    (t : ℕ → ℝ) (π : ℕ → EuclideanSpace ℝ (Fin n)) (k : ℕ → ι)
    (hrun : IsSubgradientRun c v t π k) (ht : StepSizeCond t)
    (hbdd : Bornology.IsBounded (Set.range π)) :
    ∀ J : ℕ, ∃ Jstar : ℕ, J < Jstar ∧ ∃ y : ℕ → ℝ, CoreFeasible v k J Jstar y := by sorry

end HeldWolfeCrowder.CoreProblem

