import Mathlib
import Definitions.Def_SpectralProjGrad_Shared_IsProjOnto
import Definitions.Def_SpectralProjGrad_Shared_IsConstrainedStationary
import Definitions.Def_SpectralProjGrad_SPG2_IsSPG2Run

namespace SpectralProjGrad.SPG2

/-- Theorem 2.1, second clause: every accumulation point `x̄` of the sequence `{x_k}` generated by
Algorithm SPG2 (when Step 1 never stops) is a constrained stationary point:
`⟨g(x̄), x - x̄⟩ ≥ 0` for all `x ∈ Ω`. -/
theorem accumulation_point_stationary {n : ℕ}
    {Ω U : Set (EuclideanSpace ℝ (Fin n))} {f : EuclideanSpace ℝ (Fin n) → ℝ}
    {P : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n)}
    {M : ℕ} {αmin αmax γ σ₁ σ₂ : ℝ}
    (hΩ_closed : IsClosed Ω) (hΩ_convex : Convex ℝ Ω)
    (hU_open : IsOpen U) (hΩU : Ω ⊆ U) (hf : ContDiffOn ℝ 1 f U)
    (hP : SpectralProjGrad.Shared.IsProjOnto Ω P)
    (hM : 1 ≤ M) (hαmin : 0 < αmin) (hαmin_lt : αmin < αmax)
    (hγ : γ ∈ Set.Ioo 0 1) (hσ₁ : 0 < σ₁) (hσ₁₂ : σ₁ < σ₂) (hσ₂ : σ₂ < 1)
    {x : ℕ → EuclideanSpace ℝ (Fin n)} {α : ℕ → ℝ}
    (hrun : IsSPG2Run Ω f P M αmin αmax γ σ₁ σ₂ x α)
    (xbar : EuclideanSpace ℝ (Fin n)) (hxbar : MapClusterPt xbar Filter.atTop x) :
    SpectralProjGrad.Shared.IsConstrainedStationary Ω f xbar := by sorry

end SpectralProjGrad.SPG2

