import Mathlib
import Definitions.Def_HeldWolfeCrowder_CoreProblem_Setting

namespace HeldWolfeCrowder.CoreProblem

open scoped InnerProductSpace
open Filter Topology

/-- **Held, Wolfe & Crowder (1974), Theorem 6.1, p. 80 — stated for the step-size rule (2.7).**
The paper prints the hypothesis "(2.6), (2.8)", but its proof uses `w(π^j) → w*`, which is the
consequence of (2.7) quoted just above the theorem (§6's standing assumption); this statement
uses (2.7). If for every `π ≠ 0` some `v_k` has `π·v_k < 0`, and `w` is bounded above, then
every sequence `{π^j}` generated by (2.6) with positive step sizes satisfying (2.7) is bounded. -/
theorem bounded_iterates {n : ℕ} {ι : Type*} [Fintype ι] [Nonempty ι]
    (c : ι → ℝ) (v : ι → EuclideanSpace ℝ (Fin n)) (hw : BddAbove (Set.range (w c v)))
    (hdir : ∀ π : EuclideanSpace ℝ (Fin n), π ≠ 0 → ∃ k, ⟪π, v k⟫_ℝ < 0)
    (t : ℕ → ℝ) (π : ℕ → EuclideanSpace ℝ (Fin n)) (k : ℕ → ι)
    (hrun : IsSubgradientRun c v t π k) (ht : StepSizeCond t) :
    Bornology.IsBounded (Set.range π) := by sorry

end HeldWolfeCrowder.CoreProblem
