import Mathlib
import Definitions.Def_OnlineConvexOpt_OnlineBoosting_Algorithm
import Definitions.Def_OnlineConvexOpt_OnlineBoosting_WOCL

namespace OnlineConvexOpt.OnlineBoosting

/-- Theorem 12.4, "Main" (Hazan, *Introduction to Online Convex Optimization*, 2nd ed.,
arXiv:1909.05207v3, p. 200, PDF p. 222). The predictions `x_t` generated by Algorithm 36 with
`δ = √(D²/(γN))`, `η_i = min{2/i,1}` satisfy
`∑_{t=1}^T f_t(x_t) - min_{h⋆∈CH(H)}∑_{t=1}^T f_t(h⋆(a_t)) ≤ (5dGDT)/(γ√N) + (2GD/γ)Regret_T(W)`.

`CH(H)` (the convex hull of the hypothesis class `H`) is `convexHull ℝ H`, viewing `H` as a set
in the function space `A → EuclideanSpace ℝ (Fin n)`. `RegretBoundW` is the weak learner's own
regret bound, a hypothesis of the theorem (via `hWOCL`, one `γ`-WOCL guarantee per stage
`i ∈ [1,N]`), not the boosting algorithm's own regret, which is exactly the conclusion. `hfG`
bounds the gradient of every `f t` over all of `E`, not just over `K`: the chapter's own standing
assumption (p. 198/PDF 220, "we assume that the loss functions `f ∈ F` are defined over all of
`R^d` to enable valid decisions outside of `K`") is needed because Algorithm 36's un-projected,
`1/γ`-scaled stage iterates `x^{i-1}_t` generally leave `K`, and Lemma 12.3's proof bounds `f t`'s
gradient there. -/
theorem online_boosting_regret
    {n : ℕ} (d : ℕ) (hd : d = n)
    (K : Set (EuclideanSpace ℝ (Fin n))) (hKconv : Convex ℝ K) (hKne : K.Nonempty)
    (D G : ℝ) (hDpos : 0 < D) (hGpos : 0 < G) (hD : ∀ x ∈ K, ∀ y ∈ K, dist x y ≤ D)
    (γ : ℝ) (hγpos : 0 < γ) (hγ1 : γ ≤ 1)
    (N T : ℕ) (hN : 0 < N) (hT : 0 < T)
    (δ : ℝ) (hδ : δ = Real.sqrt (D ^ 2 / (γ * N)))
    (η : ℕ → ℝ) (hη : ∀ i : ℕ, 1 ≤ i → η i = min (2 / (i : ℝ)) 1)
    (A : Type*) (a : ℕ → A) (H : Set (A → EuclideanSpace ℝ (Fin n)))
    (f : ℕ → EuclideanSpace ℝ (Fin n) → ℝ) (hfconv : ∀ t, ConvexOn ℝ K (f t))
    (hfG : ∀ t, ∀ x, ∀ v, HasGradientAt (f t) v x → ‖v‖ ≤ G)
    (W x : ℕ → ℕ → EuclideanSpace ℝ (Fin n))
    (fstage : ℕ → ℕ → EuclideanSpace ℝ (Fin n) → ℝ)
    (xplay : ℕ → EuclideanSpace ℝ (Fin n))
    (hrun : IsOnlineBoostingRun K γ δ G N T η a f W x fstage xplay)
    (RegretBoundW : ℝ)
    (hWOCL : ∀ i : ℕ, 1 ≤ i → i ≤ N →
      IsGammaWOCL K γ T a H (fun t => W t i) (fun t => fstage t i) RegretBoundW)
    (hstar : A → EuclideanSpace ℝ (Fin n)) (hstar_mem : hstar ∈ convexHull ℝ H)
    (hstar_min : ∀ h ∈ convexHull ℝ H,
      (∑ t ∈ Finset.Icc 1 T, f t (hstar (a t))) ≤ ∑ t ∈ Finset.Icc 1 T, f t (h (a t))) :
    (∑ t ∈ Finset.Icc 1 T, f t (xplay t)) - ∑ t ∈ Finset.Icc 1 T, f t (hstar (a t)) ≤
      (5 * d * G * D * T) / (γ * Real.sqrt N) + (2 * G * D / γ) * RegretBoundW := by sorry

end OnlineConvexOpt.OnlineBoosting

