import Mathlib
import Definitions.Def_CubicNewton_LocalQuad_IsRelaxedRun
import Definitions.Def_CubicNewton_LocalQuad_deltaMeasure

namespace CubicNewton.LocalQuad

/-- Nesterov–Polyak 2006, Theorem 3, item 3, including (3.8), p. 187, in the case `F = ℝⁿ`:
let `f″(x₀) ≻ 0` and `δ₀ ≤ 1/4`, and let `{x_k}` be generated by the relaxed method (3.5).
Then the whole sequence converges to a point `x*` which is a non-degenerate local minimum of `f`
(`f′(x*) = 0`, `f″(x*) ≻ 0`, and `x*` is a local minimizer), and for every `k ≥ 1`
`‖f′(x_k)‖ ≤ λₙ²(f″(x₀)) · (9 e^{3/2} / (16 L)) · (1/2)^{2^k}`. -/
theorem theorem3_local_quadratic {n : ℕ}
    (f : EuclideanSpace ℝ (Fin n) → ℝ)
    (g : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n))
    (H : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n) →L[ℝ] EuclideanSpace ℝ (Fin n))
    (L : ℝ)
    (hf : ∀ x, HasGradientAt f (g x) x) (hg : ∀ x, HasFDerivAt g (H x) x)
    (hL : 0 < L) (hLip : ∀ x y, ‖H x - H y‖ ≤ L * ‖x - y‖)
    (hn : 0 < n) (x : ℕ → EuclideanSpace ℝ (Fin n)) (M : ℕ → ℝ)
    (hrun : IsRelaxedRun L g H x M)
    (hpos : 0 < CubicNewton.Shared.lamMin (H (x 0))) (hδ0 : deltaMeasure L g H (x 0) ≤ 1 / 4) :
    ∃ xs : EuclideanSpace ℝ (Fin n),
      Filter.Tendsto x Filter.atTop (nhds xs) ∧ g xs = 0 ∧ 0 < CubicNewton.Shared.lamMin (H xs) ∧
      IsLocalMin f xs ∧
      ∀ k, 1 ≤ k → ‖g (x k)‖ ≤
        CubicNewton.Shared.lamMin (H (x 0)) ^ 2 * (9 * Real.exp (3 / 2) / (16 * L)) * (1 / 2 : ℝ) ^ (2 ^ k) := by sorry

end CubicNewton.LocalQuad

