import Mathlib
import Definitions.Def_ProcessingNetworks_PacketNetworks_BackPressurePolicy
import Definitions.Def_ProcessingNetworks_PacketNetworks_BPFluidModel

namespace ProcessingNetworks.PacketNetworks

/-- Lemma 12.20, Dai & Harrison p. 242 (PDF p. 258): for a packet network operating under the
back-pressure control policy `f` (the primitives' policy function), each fluid limit path
`(D̂,T̂,Ẑ)` (Definition 12.14, for the processes generated by `f`) satisfies the back-pressure
fluid equation (12.44) in addition to (12.31)-(12.36). -/
theorem back_pressure_fluid_equation
    {I J : ℕ} {Ω : Type*} (dat : PacketNetworkData I J) (S : Finset (Fin J → ℕ))
    (P : PacketPrimitives I J Ω) (hBP : IsBackPressurePolicy dat S P.f) (lam : Fin I → ℝ)
    (Dh : ℝ → Fin J → ℝ) (Th : ℝ → (Fin J → ℕ) → ℝ) (Zh : ℝ → Fin I → ℝ)
    (hFL : IsFluidLimitPath dat P S lam Dh Th Zh) :
    SatisfiesBackPressureFluidEquation dat S Dh Th Zh := by sorry

end ProcessingNetworks.PacketNetworks
