import Mathlib
import Definitions.Def_FlowJobShop_PairGroups_FlowShop
import Definitions.Def_FlowJobShop_PairGroups_AlgorithmH

namespace FlowJobShop.PairGroups

open FlowShop

/-- Proof of Lemma 11 (p. 49): the schedule generated by algorithm H from feasible group
schedules `R g` satisfies `FT(S) ≤ Σ_g f(R(g)) ≤ ⌈m/2⌉ · max_g f(R(g))`, where `⌈m/2⌉` is
`(m + 1) / 2` in `ℕ`. -/
theorem algorithmH_finishTime_le {m n : ℕ} (F : FlowShop m n)
    (R : (g : Fin ((m + 1) / 2)) → Fin (groupSize m g) → Fin n → ℝ)
    (hR : ∀ g, (F.group g).IsFeasible (R g)) :
    F.finishTime (F.algorithmH R) ≤ ∑ g, (F.group g).finishTime (R g) ∧
    ∑ g, (F.group g).finishTime (R g) ≤
      (((m + 1) / 2 : ℕ) : ℝ) * (Finset.univ : Finset (Fin ((m + 1) / 2))).fold max 0
        (fun g => (F.group g).finishTime (R g)) := by sorry

end FlowJobShop.PairGroups

