import Mathlib

namespace FirstOrderOpt.Deterministic

/-- Theorem 3.6, "in particular" instantiation — the goal theorem. `(x t, xTilde t, xBar t)` are
generated by the accelerated gradient method (3.3.4)-(3.3.6) with `μ = 0` and the specific
schedule `q t = α t = 2/(t+1)`, `γ t = t/(2L)`. Then `f(xBar k) - f(x*) ≤ 4L/(k(k+1)) V(x 0,x*)`.
`V` is pinned down to a genuine Bregman divergence (nonnegative, three-point identity (3.2.6) via
`dV`), inherited from `accelerated_gradient_recursion_bound`, whose specialization this goal is. -/
theorem accelerated_gradient_rate {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (X : Set E) (f : E → ℝ) (V : E → E → ℝ) (dV : E → E → E →L[ℝ] ℝ) (L : ℝ) (hL : 0 < L)
    (fGrad : E → E →L[ℝ] ℝ)
    (hSmooth : ∀ x ∈ X, ∀ y ∈ X, f y - f x - (fGrad x) (y - x) ≤ (L / 2) * ‖y - x‖ ^ 2)
    (hVnonneg : ∀ x ∈ X, ∀ z ∈ X, 0 ≤ V x z)
    (hVthreepoint : ∀ x ∈ X, ∀ y ∈ X, ∀ z ∈ X, V x z = V x y + (dV x y) (z - y) + V y z)
    (x xTilde xBar : ℕ → E)
    (hx : ∀ t, x t ∈ X) (hxBar : ∀ t, xBar t ∈ X) (hxTilde : ∀ t, 1 ≤ t → xTilde t ∈ X)
    (k : ℕ) (hk : 1 ≤ k)
    (hTildeDef : ∀ t : ℕ, 1 ≤ t → t ≤ k →
      xTilde t = (1 - 2 / ((t : ℝ) + 1)) • xBar (t - 1) + (2 / ((t : ℝ) + 1)) • x (t - 1))
    (hxDef : ∀ t : ℕ, 1 ≤ t → t ≤ k → ∀ y ∈ X,
      ((t : ℝ) / (2 * L)) * (fGrad (xTilde t)) (x t) + V (x (t - 1)) (x t) ≤
        ((t : ℝ) / (2 * L)) * (fGrad (xTilde t)) y + V (x (t - 1)) y)
    (hBarDef : ∀ t : ℕ, 1 ≤ t → t ≤ k →
      xBar t = (1 - 2 / ((t : ℝ) + 1)) • xBar (t - 1) + (2 / ((t : ℝ) + 1)) • x t)
    (xstar : E) (hxstar : xstar ∈ X) (hxstar_opt : ∀ y ∈ X, f xstar ≤ f y) :
    f (xBar k) - f xstar ≤ (4 * L) / ((k : ℝ) * ((k : ℝ) + 1)) * V (x 0) xstar := by sorry

end FirstOrderOpt.Deterministic
