import Mathlib

namespace FirstOrderOpt.Deterministic

/-- Theorem 3.5 (mirror descent function-value bound). `x t` is generated by the mirror-descent
update (3.2.5) with subgradient functionals `g t` (dual-norm bounded by `M`), `V` the Bregman
divergence, and `xstar` an optimal solution of `min_{x∈X} f(x)`. Then for `x̄ᵏₛ` the weighted
average (3.1.9), `f(x̄ᵏₛ) - f(x*) ≤ (Σ_{t=s}^{k} γt)⁻¹ (V(xs,x*) + (1/2)M²Σ_{t=s}^{k} γt²)`. `V` is
pinned down to a genuine Bregman divergence (nonnegative, three-point identity (3.2.6) via `dV`):
the proof telescopes Lemma 3.4's conclusion (itself derived from the raw minimality `hmin` via
`dV`) and then drops a trailing `-V(x_{k+1},x*) ≤ 0` term using nonnegativity. -/
theorem mirror_descent_bound {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (X : Set E) (f : E → ℝ) (V : E → E → ℝ) (dV : E → E → E →L[ℝ] ℝ) (M : ℝ) (hM : 0 < M)
    (x : ℕ → E) (g : ℕ → E →L[ℝ] ℝ) (γ : ℕ → ℝ)
    (hx : ∀ t, x t ∈ X) (hγ : ∀ t, 0 < γ t) (hgnorm : ∀ t, ‖g t‖ ≤ M)
    (hVnonneg : ∀ y ∈ X, ∀ z ∈ X, 0 ≤ V y z)
    (hVthreepoint : ∀ y ∈ X, ∀ z ∈ X, ∀ w ∈ X, V y w = V y z + (dV y z) (w - z) + V z w)
    (hsub : ∀ t, ∀ y ∈ X, f (x t) + (g t) (y - x t) ≤ f y)
    (hmin : ∀ t, ∀ y ∈ X, γ t * (g t) (x (t + 1)) + V (x t) (x (t + 1)) ≤
      γ t * (g t) y + V (x t) y)
    (s k : ℕ) (hsk : s ≤ k)
    (xstar : E) (hxstar : xstar ∈ X) (hxstar_opt : ∀ y ∈ X, f xstar ≤ f y)
    (xbar : E)
    (hxbar : xbar = (∑ t ∈ Finset.Icc s k, γ t)⁻¹ • ∑ t ∈ Finset.Icc s k, γ t • x t) :
    f xbar - f xstar ≤ (∑ t ∈ Finset.Icc s k, γ t)⁻¹ *
      (V (x s) xstar + (1 / 2) * M ^ 2 * ∑ t ∈ Finset.Icc s k, (γ t) ^ 2) := by sorry

end FirstOrderOpt.Deterministic
