import Mathlib

namespace FirstOrderOpt.Stochastic

open MeasureTheory

/-- Theorem 4.1 (goal theorem) — stochastic mirror descent expected convergence bound. `x t : Ω →
E` is the (random) iterate sequence generated by the stochastic mirror-descent update (4.1.6):
`x (t+1)` minimizes `u ↦ γt·(G t)(u) + V(x t, u)` over `X`, where `G t ω` is a stochastic gradient
at `x t ω` (`g` a fixed subgradient selector with `E[G t] = g(x t)` and dual-norm bound `M` on
`g`, second-moment bound `σ²` on `G t - g(x t)` per (4.1.7)). `xstar` is an arbitrary optimal
solution and `xbar` the weighted average `x̄ᵏₛ` of (3.1.9). Then
`E[f(x̄ᵏₛ)] - f* ≤ (Σ_{t=s}^k γt)⁻¹ (E[V(xs,x*)] + (M²+σ²)Σ_{t=s}^k γt²)`.

**Formalization Note.** The per-step algorithmic facts (membership in `X`, the subgradient
inequality for `f` at `x t ω`, the dual-norm bound on `g`, and the update's minimality) are stated
pointwise in the sample point `ω`, matching the pointwise style of chunk `03-deterministic`'s
milestones; only the second-moment bound and the cross term are genuine expectations over `μ`.
The hypothesis `hcross` packages "`E[⟨δt, xt-x*⟩] = 0`" directly as a plain expectation equality:
in the book's proof this is the consequence, after taking full expectation via the tower
property, of `δt = Gt - g(xt)` being conditionally mean-zero given the past and `xt` being a
function of the past — since no explicit filtration is threaded through this goal statement (the
filtration apparatus is confined to `martingale_difference_deviation_bound`, Lemma 4.1, which
supplies exactly this kind of cancellation), the post-tower-property consequence is taken as the
hypothesis here rather than re-derived from a conditional-independence hypothesis. `hintsecmom`/
`hintcross` guard `hsecmom`/`hcross`'s integrals with `Integrable`: Mathlib sets a Bochner integral
of a non-integrable function to `0` (`integral_undef`), so without these guards a non-integrable
`‖Gt-g(xt)‖²` or noise cross-term would satisfy `hsecmom`/`hcross` vacuously regardless of the
stochastic gradient's true variance or bias. -/
theorem stochastic_mirror_descent_bound
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
    (X : Set E) (f : E → ℝ) (V : E → E → ℝ) (M σ : ℝ) (hM : 0 < M) (hσ : 0 < σ)
    (x : ℕ → Ω → E) (G : ℕ → Ω → E →L[ℝ] ℝ) (g : E → E →L[ℝ] ℝ) (γ : ℕ → ℝ)
    (hx : ∀ t ω, x t ω ∈ X) (hγ : ∀ t, 0 < γ t)
    (hsub : ∀ t ω, ∀ y ∈ X, f (x t ω) + (g (x t ω)) (y - x t ω) ≤ f y)
    (hgnorm : ∀ t ω, ‖g (x t ω)‖ ≤ M)
    (hintsecmom : ∀ t, Integrable (fun ω => ‖G t ω - g (x t ω)‖ ^ 2) μ)
    (hsecmom : ∀ t, ∫ ω, ‖G t ω - g (x t ω)‖ ^ 2 ∂μ ≤ σ ^ 2)
    (hmin : ∀ t ω, ∀ y ∈ X, γ t * (G t ω) (x (t + 1) ω) + V (x t ω) (x (t + 1) ω) ≤
      γ t * (G t ω) y + V (x t ω) y)
    (xstar : E) (hxstar : xstar ∈ X) (hxstar_opt : ∀ y ∈ X, f xstar ≤ f y)
    (hintcross : ∀ t, Integrable (fun ω => γ t * (G t ω - g (x t ω)) (x t ω - xstar)) μ)
    (hcross : ∀ t, ∫ ω, γ t * (G t ω - g (x t ω)) (x t ω - xstar) ∂μ = 0)
    (s k : ℕ) (hsk : s ≤ k)
    (xbar : Ω → E)
    (hxbar : ∀ ω, xbar ω = (∑ t ∈ Finset.Icc s k, γ t)⁻¹ • ∑ t ∈ Finset.Icc s k, γ t • x t ω)
    (hintf : Integrable (fun ω => f (xbar ω)) μ)
    (hintV : Integrable (fun ω => V (x s ω) xstar) μ) :
    ∫ ω, f (xbar ω) ∂μ - f xstar ≤ (∑ t ∈ Finset.Icc s k, γ t)⁻¹ *
      (∫ ω, V (x s ω) xstar ∂μ + (M ^ 2 + σ ^ 2) * ∑ t ∈ Finset.Icc s k, (γ t) ^ 2) := by sorry

end FirstOrderOpt.Stochastic
