import Mathlib
import Definitions.Def_FlowJobShop_PairGroups_FlowShop
import Definitions.Def_FlowJobShop_PairGroups_AlgorithmH

namespace FlowJobShop.PairGroups

open FlowShop

/-- **Lemma 11** (Gonzalez–Sahni 1978, p. 49). Let `S` be the schedule generated by algorithm H
from optimal schedules `R g` of the `⌈m/2⌉` processor groups, and let `τ` be any feasible
non-preemptive schedule of the `m`-processor flow shop (in particular an OFT schedule `S*`).
Then `FT(S) ≤ ⌈m/2⌉ · FT(τ)`, where `⌈m/2⌉ = (m + 1) / 2` in `ℕ`. -/
theorem lemma_11 {m n : ℕ} (F : FlowShop m n)
    (R : (g : Fin ((m + 1) / 2)) → Fin (groupSize m g) → Fin n → ℝ)
    (hR : ∀ g, (F.group g).IsOptimal (R g))
    (τ : Fin m → Fin n → ℝ) (hτ : F.IsFeasible τ) :
    F.finishTime (F.algorithmH R) ≤ (((m + 1) / 2 : ℕ) : ℝ) * F.finishTime τ := by sorry

end FlowJobShop.PairGroups

