import Mathlib
import Definitions.Def_DiscountedDP_Stationary_Operators

namespace DiscountedDP.Stationary

open MeasureTheory ProbabilityTheory

/-- Blackwell (1965), Theorem 6(a), p. 232. The fixed point exists and is
unique by Theorem 5. The last clause applies to every measurable rule,
including rules not generated by `π`. -/
theorem theorem6a_generated_optimal
    {S A : Type*} [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    [MeasurableSpace A] [StandardBorelSpace A] [Nonempty A]
    (P : Problem S A) (π : MarkovPlan S A) (ustar : S → ℝ)
    (hu : IsBM ustar) (hfix : ∀ s, U P π ustar s = ustar s) :
    (∀ π' : MarkovPlan S A, IsGeneratedPlan π π' →
      ∀ s, I P π'.toPlan s ≤ ustar s) ∧
    (∀ ε : ℝ, 0 < ε → ∃ f : {g : S → A // Measurable g},
      IsGenerated π f ∧ ∀ s,
        ustar s - ε ≤ I P (stationary f).toPlan s) ∧
    (∀ ε : ℝ, 0 < ε → ∀ f : {g : S → A // Measurable g},
      (∀ s, ustar s - ε * (1 - P.β) ≤ T P f ustar s) →
      ∀ s, ustar s - ε ≤ I P (stationary f).toPlan s) := by sorry

end DiscountedDP.Stationary

